### ISSUE TITLE
MM-assistantMK2 et MMM-Assistant2Diplay 

### ISSUE THREAD

**Issue by ricotte38** [bugsounet/MMM-Assistant2Display#10]
Bonjour,
je me permets de communiquer en français avec vous sur ce sujet.
En effet je pense que je dois rater un étape car je n'arrive pas à faire s'entendre les 2 modules.
L'assistant affiche de liens internet mais n'affiche pas les pages web ou les video youtube.
  voici mon config.js qu'en pensez vous Merci d'avance :    
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.1/120", "192.168.1.1/24"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "fr",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [
       ,
 
      {
        module: "MMM-AssistantMk2",
        position: "bottom_left",
        config: {
           
			ui: "Classic",
            assistantConfig: {
                latitude: 45.1043204,
      longitude: 5.6833084,
              },
              addon: true,
            useDisplay: false,
            chimeOnFinish: null,
            recipes: ["with-MMM-Hotword.js"],
            mic: {
              recordProgram: "arecord",
              device: "plughw:1",
            },
			defaultProfile: "default",
profiles: {"default":
{    profileFile: "default.json",
    lang: "fr-FR"
     }
	},
  		

},
},	

{
  module: "MMM-Hotword",
  position: "bottom_left",
  config: {
    useDisplay: false,
    chimeOnFinish: null,
    recipes: ["with-AMk2v3_Jarvis.js"],
    mic: {
      recordProgram: "arecord",
      device: "plughw:1",
    },
  },
},

{
    module: "MMM-Assistant2Display",
    config: {
      ui: "AMk2", 
      displayDelay: 30 * 1000,
      scrollSpeed: 15,
      scrollStart: 1000,
      proxyPort: 8081,
      debug: false,
      verbose: false,
      sandbox: null,
      useLinks: true,
      usePhotos: true,
      useYoutube: true,
      useVolume: true,
      volumePreset: "ALSA"
    }
 },

 {
  module: "MMM-YouTube",
  position: "top_right",
},

{
    module: 'MMM-Screencast',
    position: 'top_center', // This position is for a hidden <div /> and not the screencast window
    config: {
        position: 'topCenter',
        height: 768,
        width: 1024,
    }
    },

    
    
    {
        module: 'MMM-Remote-Control',
        // uncomment the following line to show the URL of the remote control on the mirror
        // , position: 'bottom_left'
        // you can hide this module afterwards from the remote control itself
        config: {
            customCommand: {},  // Optional, See "Using Custom Commands" below
            customMenu: "custom_menu.json", // Optional, See "Custom Menu Items" below
            showModuleApiMenu: true, // Optional, Enable the Module Controls menu
            apiKey: "ee2bf00c.......",         // Optional, See API/README.md for details
        }
    },

    {
        module: "clock",
        position: "top_left"
    },
  
    
{
	module: "compliments",
	position: "lower_third",
	config: {
	   compliments: {
		  anytime: [
			 "vous etes beau aujourd'hui",
			 "voilà une bonne journée qui commence",
			 

		  ],
		  morning: [
			 "Bien dormi?",
			 "Bonne journée!",
			 "Bonjour!"
		  ],
		  evening: [
			 "Bonne soirée!",
			 "Repose toi bien!",
			 "Bonne nuit...",
			
			 
		  ]
	   }
	}
 },
    
 {
    module: 'MMM-AlexaControl',
    position: 'middle_center',
    config:{
        image: false,
        pm2ProcessName: "mm",
        vcgencmd: true
    }
},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		
		{
			module: "calendar",
			header: "Calendrier famille",
			position: "top_left",
			config: {
			   calendars: [
				  {
					 symbol: "male",
					 url: "https://calendar.google.com/calendar/ical/.........."
				  },
				 
			   ]
            }
            
            
		 },
		 {
			module: 'MMM-AirQuality',
			header: "Qualité de l'air aujourd'hui",
			position: 'top_center', // you may choose any location
			config: {
			  location: 'france/rhonealpes/isere/sud-grenoblois/vif/',
			  lang : 'fr' // the location to check the index for
			}
		},
		
		
		
			{
				module: "currentweather",
				position: "top_right",
				config: {
				   location: "Varces",
				   locationID: "3024788",  //ID from http://www.openweathermap.org/help/city_list.txt
				   appid: "ee2bf00........."
				}
			 },
             {
                module: "MMM-OpenmapWeather",
                position: "top_right",	// This can be any of the regions.
                                            // Best results in left or right regions.
                config: {
                    // See 'Configuration options' for more information.
                    location: "Varces",
                    locationID: "3024788", //Location ID from http://openweathermap.org/help/city_list.txt
                    appid: "ee2bf00.........",  //openweathermap.org API key
                          colorIcon: true
                }
            },
				
				
				{
				

				module: "weatherforecast",
				position: "top_right",
				// header: "Weather Forecast",
				config: {
				   location: "Varces",
				   locationID: "3024788",  //ID from http://www.openweathermap.org/help/city_list.txt
				   appid: "ee2bf00.........",
				   // colored: 'true',
				}
			 },
		
		 
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "Le Monde",
						url: "https://www.lemonde.fr/rss/une.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true,
				updateInterval:20000,
			}
		},
		
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "Notre Planète",
						url: "https://www.notre-planete.info/news/news.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true,
				animationSpeed: 5000, 
				updateInterval:25000,
			}
		},
 

{
	module: "alert",
	config: { 
		alert_effect: "genie",
			}
},

				
		
			
			
		
		
		
		
				
		
		
],
	
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by bugsounet** [comment]
Pouvez vous patienter quelques jours, je vais mettre en ligne la version 1.2 qui corrige de nombreux bug et ajoute des nouvelles fonctionnalitées ? 

Je reviens vers vous dès que la nouvelle version sera publiée.

**Comment by ricotte38** [comment]
Ok je vais patienter 
Merci

**Comment by ArnoCtout** [comment]
Bonjour Cédric,

Tout d'abord, merci pour ce superbe travail :), j'attends avec impatience cette nouvelle version.
Je n'ai pas encore installé le module Assistant2display.

Ayant un p'tit souci sur MK2, j'aimerai savoir si Assistant2Display règlera le problème (reprise des ui)

Description du petit problème :
   Lors d'une commande vocale pour afficher / masques des modules.
   Cela fonctionne bien avec les ui 'classic' 'classic2', la commande est comprise dans la receipe et correctement executée (affiche/masque le module)
   Pour contre en ui 'fullscreen', la commande est comprise dans la receipe, mais je n'en vois pas l'effet. 
L'ui fullscreen est au 'dessus' des autres écrans ?, la commande s'execute sur l'iframe ?

en vous remerciant par avance,

Arnoctout

**Comment by bugsounet** [comment]
Bonjour,
Bonne nouvelle ! les nouvelles versions de AMk2 et de A2D sont en cours de test !
Je suis en train d'ecrire le Wiki ;)

je pense que le problème sera résolu avec A2D v1.2, AMk2 3.2
beaucoup de nouveauté sont au programme sur A2D:
 * beaucoup plus stable
 * gestion de l'énergie de l'écran (auto power on / off)
 * gestion de l'affichage des modules (eco mode) [ce que vous demandez :)]
 * gestion des sensors de proximité (PIR)
 * gestion de MMM-Hotword ou MMM-Snowboy [nouveau module de détection]
 * gestion de la connectivé d'internet (en cas de perte de connexion internet: redémarre MagicMirror)
 * possibilité d'avoir un `welcome` personalisé au démarrage du programme
 * etc...

et sur AMk2:
 * reprise du projet par moi même
 * suppression et décodage des `addons`
 * mise en place du nouveau core pour `A2D prepare`
 * ...

donc, comme vous l'avez compris, le `repository addons` va donc disparaître tres prochainement !

Voila pourquoi je demande de patienter afin de ne pas faire de configuration qui au final ne servira que quelques jours ...
car A2D v1.2 a une configuration totalement différente.

A2D V1.2 = addons + A2D v1.1 + beaucoup, beaucoup de fix ;)

**Comment by bugsounet** [comment]
A2D v1.2 est maintenant en ligne !
n'oubliez pas de mettre a jour AssistantMk2 a jour (v3.2.0)

Comme je disais, la configuration est totalement différente,
Lisez le [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki)
Il est preférable de redémarrer la configuration avec une nouvelle installation
```sh
cd ~/MagicMirror/modules
rm -rf MMM-Assistant2Display
```
et également supprimer l'ancien champ de configuration de votre `config.js`
et reprendre l'une installation normale depuis le [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Installation#installation-v120)

En cas de souci, n'hésitez pas à revenir vers moi

**Comment by ricotte38** [comment]
Bonjour,

super travail

je vais tester cela ce soir apres le boulot...

Encore Merci

________________________________
De : Cédric <notifications@github.com>
Envoyé : jeudi 9 avril 2020 11:21
À : bugsounet/MMM-Assistant2Display <MMM-Assistant2Display@noreply.github.com>
Cc : ricotte38 <ericjoe@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [bugsounet/MMM-Assistant2Display] MM-assistantMK2 et MMM-Assistant2Diplay (#10)


A2D v1.2 est maintenant en ligne !
n'oubliez pas de mettre a jour AssistantMk2 a jour (v3.2.0)

Comme je disais, la configuration est totalement différente,
Lisez le wiki<https://github.com/bugsounet/MMM-Assistant2Display/wiki>
Il est preférable de redémarrer la configuration avec une nouvelle installation

cd ~/MagicMirror/modules

rm -rf MMM-Assistant2Display

et également supprimer l'ancien champ de configuration de votre config.js
et reprendre l'une installation normale depuis le wiki<https://github.com/bugsounet/MMM-Assistant2Display/wiki/Installation#installation-v120>

En cas de souci, n'hésitez pas à revenir vers moi

**Comment by bugsounet** [comment]
humm, j'ai bien envie d'essayer de programmer un module pour avoir la TV ...
  * soit avec `Free` avec leur flux multipost (mais il faut avoir Free comme FAI)
  * soit avec molotov ...
dans tous les cas ce sera reservé aux français (pour le moment)

Notes:
pour le moment, j'ai uniquement programmé (avec A2D) `France ::info` sur le RPI
c'est pratique, dans ma cuisine, quand je fais à manger pour la petite famille ;)

**Comment by ricotte38** [comment]
Super idée pour la tv free.J ai hâte de rester tout ça. Merci encore Le 9 avr. 2020 17:16, Cédric <notifications@github.com> a écrit :

humm, j'ai bien envie d'essayer de programmer un module pour avoir la TV ...

soit avec Free avec leur flux multipost (mais il faut avoir Free comme FAI)soit avec molotov ...

dans tous les cas ce sera reservé aux français (pour le moment)

Notes:

pour le moment, j'ai uniquement programmé (avec A2D) France ::info sur le RPI

c'est pratique, dans ma cuisine, quand je fais à manger pour la petite famille ;)

**Comment by bugsounet** [comment]
![image](https://user-images.githubusercontent.com/30669209/78937664-29f5dc00-7ab1-11ea-8b8e-005bd0655c6f.png)
un truc comme ça quoi ...

**Comment by bugsounet** [comment]
un truc de ce genre la ?
![image](https://user-images.githubusercontent.com/30669209/78937953-a092d980-7ab1-11ea-8a41-d2d6dabf9aab.png)
mais peux etre avec le design AMk2 et/ou en plein ecran

**Comment by ArnoCtout** [comment]
Bonjour Cédric,

Super idée, la tv
On peut installer molotov sur le PI ? L'ipTv c'est mort pour moi, chez bouygues obligé de passé par leur appli :(, jamais trouvé les flux

J'ai testé avec quelques retours / incompréhensions.

D'abord la question très  bete : c'est quoi photo ? Comment on le déclenche ?

Module Youtube : je cerne pas tout a fait le probleme, parfois la video ne se lance pas, ou sans le son.
j'ai reproduit le pb en faisant à l'ouverture de MM: youtube depeche mode=>OK, youtube Mickael Jackon=>OK, YT depeche mode=>s'ouvre et se referme, youtube mickeal Jackson =>ok.

Link : quand j'active les links, les receipts de MK2 ne sont pas déclenchées, cela ouvre la page web en ignorant ma receipt. Ex : avec link=false, affiche radio=>ok mon MMM apparait, link=true=>ouvre le lien. Peut on avoir les 2 : d'abord la receipt pour intercepter la cmd, puis le link si pas dans receipt

Volume: J'ai du modifié le js en ajoutant -c1 à alsa car je suis en USB pour le HP :)
Pour le controle du volume ca fonctionne sur le PI. 
J'ai fait une receipt pour controler ma TV (en test avec des bash) et pour le controle du volume je galere en peu. A chaque fois que je dis 'télé augmente le son', c'est le PI qui change de volume.
Comment gerer la commande volume ?
si 'volume' dans receipt alors commande dans receipt sinon controle du volume du PI .

Je ne suis pas sur d'avoir était clair dans mes descriptions,...

En vous remerciant par avance,

ArnoCtout

**Comment by bugsounet** [comment]
> D'abord la question très bete : c'est quoi photo ? Comment on le déclenche ?

simplement pour lire les photos qui se trouve dans `google photos`
commande simple : `mes photos`

> Module Youtube

cela dépend de pas mal de condition... par exemple les autorisations de lecture par le créateur de la vidéo

> Link

je me suis poser la question que faire ...
[code](https://github.com/bugsounet/MMM-Assistant2Display/blob/master/MMM-Assistant2Display.js#L197)
c'est prévu, j'ai eu peur de trop modifier le core de AMk2 et de générer des bug...
(il suffit d'oublier une condiftion et pouff... ça part en sucette...)
Je vais me pencher sur le problemes des `HOOK`

> Volume

tiens, il crois que le mirroir est une télé ...
en tout cas, c'est le retour des serveurs google qui donne l'ordre de changer le volume
pour simplifier : si on demande volume 100% > google returne une info `VOLUME:100` qui est envoyer a A2D
donc je ne peux pas gerer malheureusement le retour que google fait
Pour contourner, hummm... je vais faire quelques test ;)
car le gros probleme des recipes c'est que l'on passe par les serveurs de google ... bien sur il y a un réponse de serveur google mais la réponse n'est pas affiché mais ... je pense qu'avec le codage actuel la réponse est quand meme lu par A2D
donc en résumé ... meme probleme:
Je vais me pencher sur le problemes des `HOOK`


Comme quoi, ce n'est pas évident de penser a toute les possibilités et éventualités.
je me suis basé sur une utilisation basique de AMk2
maintenant, je vais coder une version plus avancé (il faut bien commencer le core du programme pour arriver a cette étape)

Merci pour votre retour,
Je vais faire au mieux ;)

**Comment by ArnoCtout** [comment]
Merci bcp des vos réponses
Pour youtube, je regarde, c'est peut etre le rpi qui se traine dans le decodage...
Pour les links : c'est juste une remarque, dans pour l'instant je n'en ai pas pas besoin.

Autres questions : 
=>vous utilisez quel navigateur web pour le HTML5 (useHTML5: true), chromium ne support pas le spreech)

ArnoCtout

**Comment by bugsounet** [comment]
electron utilise chronium, vous appeler quoi par `spreech`

**Comment by ArnoCtout** [comment]
lors de la 1ere install de mk2, je n'avais pas de retour audio. j'ai donc mis html5 à false.
Sur le web j'ai lancé avec Chromium une page de test HTML5, dans la partie audio Chromium n'est pas compatible html5 'Spreech synthesis'

**Comment by bugsounet** [comment]
on utilise pas la synthese vocale, uniquement un fichier audio que google nous envoie.

Au départ on avait demander a google de nous envoyer un fichier `wav`.
Mais cela demande beaucoup de réception de donnée (donc beaucoup de ressources) ...
Puis on est passer au `mp3` pour un gain en temps de réponse (et de réception de donnée)
et donc on demande a le lire via HTML5 audio()
Mais cela dépend de la configuration audio (.asoundrc) et de la configuration complete (USB/bluetooth/...)

Le second codeur de AMk2 était contre revenir sur une double version sonore (HTML5 sur false)
J'ai du 'taper du point sur la table' pour se mettre d'accord... afin que pour les personnes dans votre cas, puisse avoir enfin du son !

A noter : depuis peu, j'ai récupérer complètement AMk2 (owner) et Hotword

**Comment by ricotte38** [comment]
Bonjour,

super idée la tv freebox je suis preneur à 100%.

J'ai un problème car les vidéos youtube ne se lance pas à ma demande, l'assistant se lance et

-  soit reste sur les 3 petits points qui forment une vague en mouvement en bloquant l’accès au miroir

- soit annonce la recherche  et la vidéo ne se lance pas (écran noir de la vidéo intégrée à la page web youtube??

Par ailleurs je me demande s'il ne me manque pas quelque chose, ai je besoin d'un module complémentaire à amk2+A2D pour que cela fonctionne?

est ce que les vidéos youtube doivent se charger en pleine page?

Merci par avance de tes réponses et désolé d’être un boulet....

**Comment by bugsounet** [comment]
> address: "0.0.0.0", 

Le probleme est ici

youtube prefere `localhost`, je vais regarder le remote-control afin d' avoir un mix de configuration possible

dans tous les cas, tant que l'adresse ne sera pas ça, cela ne fonctionnera pas :(
les vidéos sont systématiquement refusé par youtube

**Comment by ricotte38** [comment]
Merci , En effet cela aura un conflit avec le Remote control...je vais peut-être devoir faire un choix...Si tu as un solution,  je reste preneur Merci beaucoup Le 11 avr. 2020 12:33, Cédric <notifications@github.com> a écrit :



address: "0.0.0.0",



Le probleme est ici

youtube prefere localhost, je vais regarder le remote-control afin d' avoir un mix de configuration possible

dans tous les cas, tant que l'adresse ne sera pas ça, cela ne fonctionnera pas :(

les vidéos sont systématiquement refusé par youtube

**Comment by bugsounet** [comment]
j'aurai besoin de plus d'information afin de ma rapprocher au plus de votre utilisation et bien sur faire quelques test simple de mon coté

utiliser-vous simplement remote-control via votre reseau local ? (wifi)
dans ce cas, c'est relativement simple ;)

je vais faire quelques test ;)

**Comment by ricotte38** [comment]
Oui en effet seulement en wifi.Merci Le 11 avr. 2020 12:57, Cédric <notifications@github.com> a écrit :

j'aurai besoin de plus d'information afin de ma rapprocher au plus de votre utilisation et bien sur faire quelques test simple de mon coté

utiliser-vous simplement remote-control via votre reseau local ? (wifi)

dans ce cas, c'est relativement simple ;)

je vais faire quelques test ;)

**Comment by bugsounet** [comment]
j'ai essayé plusieurs possibilités, malheureusement cela ne fonctionne pas.
je suis bloqué avec la limitation de l'API de youtube qui veux que ce soit absolument `localhost`

**Comment by ricotte38** [comment]
Je viens effectivement de tester avec "localhost" et cela  fonctionne très bien, mais pas moyen de faire fonctionner le "remote control" :-( 
c'est vrai que le contrôle à distance via le telephone en cas de bug évite de devoir allumer le pc pour lancer un redémarrage du miroir. peut être y a t il une autre solution que remote control?

- Sinon comment peut on écouter ou regarder les actualités avec AMK2? Podcast ou autre?

Merci encore.

**Comment by ricotte38** [comment]
Ah oui une dernière question:

lorsque l'on lance une playlist youtube avec seulement de la musique, comment faire pour je puisse revoir tous les autres modules tout en concevant évidemment la musique? 
vaut il mieux utiliser un module musique dédie pour cela? j'ai deezer premium et spootify, lequel fonctionnerait le mieux avec AMK2?

Merci

**Comment by bugsounet** [comment]
pour le moment, je n'ai pas encore programmer cela.
pour les info j'utilise le flux youtube de france info

j'ai utiliser IFTTT pour rediriger "mets les infos" vers une réponse vocale avec le lien de Youtube.
du coup, A2D ouvre YT avec le lien
Inconveniant: il dit le lien YT a haute voix

ce qu'il faudrai que je fasse (ou coder) : faire un recipe sur AMk2 avec un transcriptionHook et envoyer une réponse pour A2D avec un lien personalisé

--- 
> lorsque l'on lance une playlist youtube avec seulement de la musique, comment faire pour je puisse revoir tous les autres modules tout en concevant évidemment la musique?

pour le moment pas possible et je pense que je ne le ferai pas ...
pourquoi ?
simplement car regarder une vidéo demande beaucoup de ressources pour un RPI.
c'est pourquoi que j'ai desactivé tous les modules afin d'avoir un maximum de fluidité en plein écran
(j'ai gagné environ 80% de fljuidité avec cette méthode) 
a savoir que lors de mes premier tests sur RPI j'avais 10 images par secondes et le RPI qui Freeze...
j'essai de faire un compromis (car il faut toutefois se mettre dans la tete que c'est qu'un RPI...)

> vaut il mieux utiliser un module musique dédie pour cela? j'ai deezer premium et spootify, lequel fonctionnerait le mieux avec AMK2?

essayez [`raspotify`](https://github.com/dtcooper/raspotify) et [`MMM-Spotify`](https://github.com/eouia/MMM-Spotify)  avec le [recipe AMk2 qui va bien](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Prepared-recipes#with-mmm-spotifyjs)

**Comment by ricotte38** [comment]
Merci pour vos retours, je regarde ce qui est le plus simple pour mon usage. En effet je prends mes marques et j'occulte la puissance de la bête.
Je vais regarder si je trouve une combinaison pour un remote en localhost

Merci

**Comment by bugsounet** [comment]
sinon un autre petit module que j'utilise pour le remote:
![image](https://user-images.githubusercontent.com/30669209/79044834-de097b00-7c07-11ea-97e7-6602e667f26d.png)
[MMM-TelegramBot](https://github.com/eouia/MMM-TelegramBot)

**Comment by ricotte38** [comment]
Cool je vais tester cela, 
les commandes en français sont à paramétrer je pense?

**Comment by bugsounet** [comment]
on avait commencé a les mettres en français avec @eouia mais il a mis des nouvelles fonctions en place, donc elle ne sont pas traduite

**Comment by bugsounet** [comment]
telegram c'est un peu comme 'messenger' ... j'ai pas mal de contact qui ont besoin d'assistance sur mes modules :p

**Comment by bugsounet** [comment]
si vous avez installer Télégram n'hesitez pas a m'ajouter ;) (@bugsounet)
sinon, en cas de probleme réouvrez cette issue ;)
