### ISSUE TITLE
A2Dserver,stopcommand 

### ISSUE THREAD

**Issue by thierry97** [bugsounet/MMM-Assistant2Display#100]
bonjour,
J'ai un soucis avec la commande stop pour arrêter la radio, YouTube, etc... j'ai pourtant suivi les instructions données.

**Comment by bugsounet** [comment]
Bonjour,

Pouvez-vous configurer GA en essayant [ceci](https://github.com/bugsounet/MMM-GoogleAssistant/wiki/FR-Structure#champ-a2dserver) pour le champ `A2DServer: {}` 

le `stopCommand` doit être personnaliser pour un bon fonctionnement.

Désolé, je fais le wiki en français petit à petit..

**Comment by thierry97** [comment]
oui j'ai déja essayé avec la commande suivante : 
A2DServer: {
			  useA2D: true,
			  stoppe: "stop"
mais ça n'a pas fonctionné non plus. Lorsque j'appel Jarvis pendant que youtube ou bien la radio est en marché celui ci ne réagit pas à mon appel. 

Merci déja pour le travail que vous étez entrain de fournir

**Comment by bugsounet** [comment]
Désolé d'insister...

Sur le lien donné, actuellement, je lis:
```
A2DServer: {
  useA2D:true,
  stopCommand: "stoppe"
},
```

```
useA2D: Cette option active le code préconfiguré pour l'utilisation de MMM-Assistant2Display
stopCommand: Commande personnalisée pour stopper les actions en cours de Assistant2Display
Pour l'utilisateur français: Vous devez régler votre stopCommand en stoppe
```

ceci n'est pas dans le lien donné ? n'est ce pas français ?
Je ne sais pas quoi faire de plus actuellement pour vous
