### ISSUE TITLE
Spotify launches in a web browser

### ISSUE THREAD

**Issue by Beastlynoob** [bugsounet/MMM-Assistant2Display#103]
Sorry to bother you,

When I tell my google assistant to play for example "Alen Walker on Spotify". It will show me the link at the bottom of the screen then launch a browser and open alan walker through Spotify. Since Spotify has disabled web player years ago the music won't play but instead, it will show me a playlist of Alan Walker music. Is their a way so that it launches Spotify instead of going to chromium. Sorry, I am new to the magic mirror and Rasberry pi. BTW I love your modules and I am so glad you made these. THANK YOU!!!

**Comment by bugsounet** [comment]
Hi,
Your result is spotify module is not activated.
Spotify module don't play music with chrome/chronium but with an external program
If you don't activate it, A2D will open the link found (if link module activated) and will play anything (just display the link found)
Please read wiki doc of spotify for activate it

**Comment by Beastlynoob** [comment]
I doubled checked that I did the npm run Spotify and the NPN run libresoft. I have installed both but still have the issue. And just to confirm, the connect to section in the spotify part of the config.js file should say connectTo: "Librespot", right?

**Comment by bugsounet** [comment]
so if it's display a web page, it still not activated
can you show me your GA/A2D config ?

**Comment by Beastlynoob** [comment]
sure here it is:`

{
  module: "MMM-GoogleAssistant",
  position: "fullscreen_above",
  config: {
    debug: false,
    assistantConfig: {
      lang: "en-US",
      projectId: "mymirror1-f7126", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: 33.038334,
      longitude: -97.006111  ,
    },
    responseConfig: {
      useScreenOutput: true,
      screenOutputCSS: "screen_output.css",
      screenOutputTimer: 5000,
      activateDelay: 250,
      useAudioOutput: true,
      useChime: true,
      newChime: false,
      useNative: true,
      playProgram: "mpg321"
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:2",
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    snowboy: {
      audioGain: 2.0,
      Frontend: true,
      Model: "jarvis",
      Sensitivity: null
    },
    A2DServer: {
      useA2D: true,
      stopCommand: "stop"
    },
    recipes: [ "with-MMM-TelegramBot.js" ]
  }
},
{
  module: "MMM-Assistant2Display",
  position: "top_left",
  config: {
    debug:false,
    useYoutube: true,
    links: {
      useLinks: true,
      displayDelay: 60 * 1000,
      scrollStep: 25,
      scrollInterval: 1000,
      scrollStart: 5000,
      scrollActivate: false,
      verbose: false
    },
    photos: {
      usePhotos: true,
      displayDelay: 10 * 1000
    },
    volume: {
      useVolume: true,
      volumePreset: "ALSA",
      myScript: null
    },
    briefToday: {
      useBriefToday: false,
      welcome: "brief Today"
    },
    TelegramBot: {
      useTelecastSound: false,
      TelecastSound: "TelegramBot.ogg"
    },
    cast: {
      useCast: false,
      castName: "MagicMirror_A2D",
      port: 8569
    },
    spotify: {
      useSpotify: false,
      useIntegred: false,
      useLibrespot: true,
      connectTo: "Librespot",
      playDelay: 3000,
      minVolume: 10,
      maxVolume: 100,
      updateInterval: 1000,
      idleInterval: 10000,
      username: "",
      password: "",
      CLIENT_ID: "",
      CLIENT_SECRET: "",
      deviceDisplay: "Listening on",
      usePause: true
    }
  }
},
`

**Comment by bugsounet** [comment]
> Your result is spotify module is not activated.
> edit: added [full sample](https://github.com/bugsounet/MMM-Assistant2Display/wiki/spotify#full-sample)

sorry but i can't do more and better for you ...
Please read and correct ...

Note: 
I considere that you don't share any personal identifiant field. 
That's why you put `""` (username, password, CLIEND_ID,CLIENT_SECRET)
If this is not the case ... I really ask myself questions ...

**Comment by Aarish12** [comment]
Here is a picture of what it shows when I say Allen walker on Spotify. I have followed all the steps and even tried reinstalling the modules.

![630097C3-A230-433A-B717-F24283DCAD81](https://user-images.githubusercontent.com/66502395/89112394-98c3c000-d427-11ea-9bbe-2dab66d707c3.jpeg)

**Comment by bugsounet** [comment]
> > Your result is spotify module is not activated.
> > edit: added [full sample](https://github.com/bugsounet/MMM-Assistant2Display/wiki/spotify#full-sample)
> 
> sorry but i can't do more and better for you ...
> Please read and correct ...
> 
> Note:
> I considere that you don't share any personal identifiant field.
> That's why you put `""` (username, password, CLIEND_ID,CLIENT_SECRET)
> If this is not the case ... I really ask myself questions ...

**Comment by Aarish12** [comment]
Sorry I am very confused. How do I activate it. If I am not mistakes you go to the A2D folder through terminal and do npm run Spotify.

**Comment by bugsounet** [comment]
Wow :/

in the link [https://github.com/bugsounet/MMM-Assistant2Display/wiki/spotify#full-sample](https://github.com/bugsounet/MMM-Assistant2Display/wiki/spotify#full-sample) as the full sample link give

You will see the Spotify config : 
```js
    spotify: {
      useSpotify: true, // activate spotify module
      useIntegred: true, // activate visual of spotify listening on any device
      useLibrespot: true, // activate spotify audio playing
      connectTo: "Librespot", // define the name of MagicMirror spotify device 
      playDelay: 3000, // wait 3sec to start music
      minVolume: 10, // Volume to set when assistant is speaking
      maxVolume: 100, // volume to set on the start of the device
      updateInterval: 1000, // update interval for display new data (useIntegred is needed)
      idleInterval: 10000, // update interval on idle: delay to search if music is played (useIntegred needed)
      username: "", // define this with your spotify email (useLibrespot needed)
      password: "", // define this with your password (useLibrespot needed)
      CLIENT_ID: "", // define your CLIENT_ID (useIntegred needed)
      CLIENT_SECRET: "", // define your CLIENT_SECRET (useIntegred needed)
      deviceDisplay: "Listening on", // replace this value by your language
      usePause: true // Use stop or pause when librespot finish to play (useLibrespot needed)
    }
```

and this is your actual config (and i comment it for more understanding):
```js
spotify: {
  useSpotify: false, // don't activate spotify module
  useIntegred: false, // don't activate visual of spotify
  useLibrespot: true, // activate spotify audio playing but desactived because spotify module is not activated
  connectTo: "Librespot", // define the name of MagicMirror spotify device as Librespot
  playDelay: 3000, // wait 3sec to start music
  minVolume: 10, // Volume to set when assistant is speaking
  maxVolume: 100, // volume to set on the start of the device
  updateInterval: 1000, // update interval for display new data (useIntegred is needed)
  idleInterval: 10000, // update interval on idle: delay to search if music is played (useIntegred needed)
  username: "", // define this with your spotify email (useLibrespot needed)
  password: "", // define this with your password (useLibrespot needed)
  CLIENT_ID: "", // define your CLIENT_ID (useIntegred needed)
  CLIENT_SECRET: "", // define your CLIENT_SECRET (useIntegred needed)
  deviceDisplay: "Listening on", // replace this value by your language
  usePause: true // Use stop or pause when librespot finish to play (useLibrespot needed)
}
```
so if you not activate spotify by `useSpotify: true` like my sample it will never work

**Comment by Beastlynoob** [comment]
Unfortunately this still isn't working. Now when I tell it to play something on Spotify it will show me the link but then not do anything. And I did put the credentials in the config.js file, I just removed them when pasting them to the issue page.

**Comment by bugsounet** [comment]
in all case now, the module is active with my spotify proposal config
now if don't work:
 * the cause can be only about the 4 needed credentials fields
 * or you have no spotify premium account

Note: 
if you change `username` (your spotify email) and `password` (your spotify password) field, it is important to restart your rpi to load the new configuration (restart the mirror will not work)
