### ISSUE TITLE
Youtube displays error screen when activated

### ISSUE THREAD

**Issue by yurMoThEr** [bugsounet/MMM-Assistant2Display#104]
Here's my config file:

var config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	electronOptions: {
	    webPreferences: {
	    webviewTag: true
	  }
	},
	port: 8080,
	//ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
       	ipWhitelist: [],	                     	                                // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [  
		{
		  module: "MMM-GoogleAssistant",
		  position: "fullscreen_above",
		  config: {
		    assistantConfig: {
		      latitude: 43.772099,
		      longitude: -79.344490,
		    },
		    micConfig: { // put there configuration generated by auto-installer
		      recorder: "arecord",
		      device: "plughw:1",
		    },
		    snowboy: {
		      Model: "smart_mirror",
		    },
		    A2DServer: {
		  useA2D: true,
		    },
		  },
		},
		{
		  module: "MMM-Assistant2Display",
		  position: "top_left",
		  config: {
		    debug:false,
		    useYoutube: true,
		    links: {
		      useLinks: true,
		      displayDelay: 60 * 1000,
		      scrollStep: 25,
		      scrollInterval: 1000,
		      scrollStart: 5000,
		      scrollActivate: true,
		      verbose: false
		    },
		    photos: {
		      usePhotos: true,
		      displayDelay: 10 * 1000
		    },
		    volume: {
		      useVolume: true,
		      volumePreset: "ALSA",
		      myScript: null
		    },
		    briefToday: {
		      useBriefToday: true,
		      welcome: "Brief today"
		    },
		    screen: {
		      useScreen: true,
		      delay: 5 * 60 * 1000,
		      turnOffDisplay: true,
		      ecoMode: false,
		      displayCounter: true,
		      displayBar: false,
		      displayStyle: "Text",
		      text: "Auto Turn Off Screen:",
		      detectorSleeping: false,
		      governorSleeping: false,
		      rpi4: false
		    },
		    internet: {
		      useInternet: true,
		      displayPing: false,
		      delay: 2* 60 * 1000,
		      scan: "google.fr",
		      command: "sudo reboot",
		      showAlert: true
		    },
		    cast: {
		      useCast: true,
		      castName: "MagicMirror_A2D",
		      port: 8569
		    },
		    spotify: {
		      useSpotify: true,
		      useIntegred: true,
		      useLibrespot: false,
		      connectTo: null,
		      playDelay: 1,
		      minVolume: 10,
		      maxVolume: 100,
		      updateInterval: 1000,
		      idleInterval: 10000,
		      username: "",
		      password: "",
		      CLIENT_ID: "17150c4b1bee49a0b123aa11f9a668bc",
		      CLIENT_SECRET: "66ae1dd70d4c4040a480c7ff90992507",
		      deviceDisplay: "Listening on",
		      usePause: true
		    }
		  }
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

When I say Michael Jackson Thriller after activation, an error screen appears for a split second and disappears. I have found errors in the frontend and backend logs;

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.12.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2020-08-02 17:32:03.607] [LOG]    Starting MagicMirror: v2.12.0
[2020-08-02 17:32:03.622] [LOG]    Loading config ...
[2020-08-02 17:32:03.636] [LOG]    Loading module helpers ...
[2020-08-02 17:32:05.724] [LOG]    Initializing new module helper ...
[2020-08-02 17:32:05.726] [LOG]    Module helper loaded: MMM-GoogleAssistant
[2020-08-02 17:32:07.791] [LOG]    Initializing new module helper ...
[2020-08-02 17:32:07.792] [LOG]    Module helper loaded: MMM-Assistant2Display
[2020-08-02 17:32:07.792] [LOG]    All module helpers loaded.
[2020-08-02 17:32:08.027] [LOG]    Starting server on port 8080 ... 
[2020-08-02 17:32:08.031] [INFO]   You're using a full whitelist configuration to allow for all IPs
[2020-08-02 17:32:08.042] [LOG]    Server started ...
[2020-08-02 17:32:08.044] [LOG]    Connecting socket for: MMM-GoogleAssistant
[2020-08-02 17:32:08.046] [LOG]    Connecting socket for: MMM-Assistant2Display
[2020-08-02 17:32:08.047] [LOG]    Sockets connected & modules started ...
[2020-08-02 17:32:08.251] [LOG]    Launching application.
[2020-08-02 17:32:10.852] [LOG]    [ASSISTANT] MMM-GoogleAssistant Version: 2.4.0
[2020-08-02 17:32:10.998] [LOG]    [A2D] MMM-Assistant2Display Version: 2.3.5
[2020-08-02 17:32:11.214] [LOG]    [SNOWBOY] Model selected: smart_mirror
[2020-08-02 17:32:11.219] [LOG]    [SNOWBOY] snowboy v1.5.0 Initialized...
[2020-08-02 17:32:11.232] [LOG]    [ASSISTANT] Assistant2Display Server Started
[2020-08-02 17:32:11.234] [LOG]    [ASSISTANT] Google Assistant is initialized.
**### _[2020-08-02 17:32:11.570] [ERROR]  Whoops! There was an uncaught exception...
[2020-08-02 17:32:11.580] [ERROR]  TypeError: Cannot read property 'stop' of undefined
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_helper.js:1:966)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:112:11)
    at Socket.emit (events.js:200:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:82:9)_
[2020-08-02 17:32:11.609] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?**
[2020-08-02 17:32:11.612] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[2020-08-02 17:32:11.699] [LOG]    [SCREEN] Screen v1.0.3 Initialized...
[2020-08-02 17:32:11.789] [LOG]    [INTERNET] Internet v1.0.0 Initialized...
[2020-08-02 17:32:11.798] [LOG]    [CAST] Cast v1.0.0 Initialized...
[2020-08-02 17:32:11.879] [LOG]    [A2D] Assistant2Display is initialized.

Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/en.json
translator.js:227 Loading core translation fallback file: translations/en.json
loader.js:175 Load script: modules/MMM-GoogleAssistant//MMM-GoogleAssistant.js
module.js:486 Module registered: MMM-GoogleAssistant
loader.js:147 Bootstrapping module: MMM-GoogleAssistant
loader.js:175 Load script: /modules/MMM-GoogleAssistant/components/response.js
loader.js:152 Scripts loaded for: MMM-GoogleAssistant
loader.js:194 Load stylesheet: /modules/MMM-GoogleAssistant/MMM-GoogleAssistant.css
loader.js:154 Styles loaded for: MMM-GoogleAssistant
translator.js:175 MMM-GoogleAssistant - Load translation fallback: translations/en.json
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
  protocols.This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
 - http://0.0.0.0:8080/css/main.css
- http://0.0.0.0:8080/fonts/roboto.css
- http://0.0.0.0:8080/socket.io/socket.io.js
- http://0.0.0.0:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://0.0.0.0:8080/js/defaults.js
- http://0.0.0.0:8080/config/config.js
- http://0.0.0.0:8080/vendor/vendor.js
- http://0.0.0.0:8080/modules/default/defaultmodules.js
- http://0.0.0.0:8080/js/logger.js
- http://0.0.0.0:8080/translations/translations.js
- http://0.0.0.0:8080/js/translator.js
- http://0.0.0.0:8080/js/class.js
- http://0.0.0.0:8080/js/module.js
- http://0.0.0.0:8080/js/loader.js
- http://0.0.0.0:8080/js/socketclient.js
- http://0.0.0.0:8080/js/main.js
- http://0.0.0.0:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://0.0.0.0:8080/translations/en.json
- http://0.0.0.0:8080/translations/en.json
- http://0.0.0.0:8080/modules/MMM-GoogleAssistant//MMM-GoogleAssistant.js
- http://0.0.0.0:8080/modules/MMM-GoogleAssistant/components/response.js
- http://0.0.0.0:8080/modules/MMM-GoogleAssistant/MMM-GoogleAssistant.css
  
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
(anonymous) @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145
loader.js:156 Translations loaded for: MMM-GoogleAssistant
loader.js:175 Load script: modules/MMM-Assistant2Display//MMM-Assistant2Display.js
module.js:486 Module registered: MMM-Assistant2Display
loader.js:147 Bootstrapping module: MMM-Assistant2Display
MMM-Assistant2Display.js:1 [A2D] Scan config.js file
MMM-Assistant2Display.js:1 [A2D] Auto choice UI: Fullscreen
loader.js:175 Load script: /modules/MMM-Assistant2Display/components/display.js
loader.js:175 Load script: /modules/MMM-Assistant2Display/ui/Fullscreen/Fullscreen.js
loader.js:175 Load script: /modules/MMM-Assistant2Display/components/youtube.js
loader.js:175 Load script: /modules/MMM-Assistant2Display/components/progressbar.js
loader.js:175 Load script: /modules/MMM-Assistant2Display/components/spotify.js
loader.js:194 Load stylesheet: https://cdn.materialdesignicons.com/5.2.45/css/materialdesignicons.min.css
loader.js:175 Load script: https://code.iconify.design/1/1.0.6/iconify.min.js
loader.js:152 Scripts loaded for: MMM-Assistant2Display
loader.js:194 Load stylesheet: /modules/MMM-Assistant2Display/ui/Fullscreen/Fullscreen.css
loader.js:194 Load stylesheet: modules/MMM-Assistant2Display/screen.css
loader.js:194 Load stylesheet: vendor/css/font-awesome.css
loader.js:154 Styles loaded for: MMM-Assistant2Display
translator.js:175 MMM-Assistant2Display - Load translation fallback: translations/en.json
loader.js:156 Translations loaded for: MMM-Assistant2Display
loader.js:194 Load stylesheet: css/custom.css
display.js:1 [A2D] DisplayClass Loaded
Fullscreen.js:4 [A2D] Extend Display with Fullscreen ui Loaded
spotify.js:1 [A2D] Spotify Loaded
MMM-Assistant2Display.js:1 [A2D] initialized.
main.js:496 All modules started!
module.js:195 MMM-GoogleAssistant is suspended.
spotify-xxl.png:1 GET http://0.0.0.0:8080/modules/MMM-Spotify/resources/spotify-xxl.png 404 (Not Found)
Image (async)
getCoverContainer @ spotify.js:1
getMinimalistBarDom @ spotify.js:1
prepare @ spotify.js:1
notificationReceived @ MMM-Assistant2Display.js:1
sendNotification @ main.js:96
(anonymous) @ main.js:64
Promise.then (async)
createDomObjects @ main.js:63
modulesStarted @ main.js:499
startModules @ loader.js:56
(anonymous) @ loader.js:38
stylesheet.onload @ loader.js:201
load (async)
loadFile @ loader.js:199
loadNextModule @ loader.js:36
(anonymous) @ loader.js:29
(anonymous) @ loader.js:122
(anonymous) @ loader.js:158
(anonymous) @ translator.js:186
xhr.onreadystatechange @ translator.js:22
XMLHttpRequest.send (async)
loadJSON @ translator.js:25
load @ translator.js:180
loadTranslations @ module.js:330
(anonymous) @ loader.js:155
loadNextDependency @ module.js:296
(anonymous) @ module.js:293
stylesheet.onload @ loader.js:201
load (async)
loadFile @ loader.js:199
loadFile @ loader.js:252
loadNextDependency @ module.js:291
(anonymous) @ module.js:293
stylesheet.onload @ loader.js:201
load (async)
loadFile @ loader.js:199
loadFile @ loader.js:259
loadNextDependency @ module.js:291
(anonymous) @ module.js:293
stylesheet.onload @ loader.js:201
youtube.js:1 [A2D] YOUTUBE Class Loaded
3www-widgetapi.js:555 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://0.0.0.0:8080').
q.R @ www-widgetapi.js:555
q.Y @ www-widgetapi.js:552
setInterval (async)
ze @ www-widgetapi.js:353
Kh @ www-widgetapi.js:553
Y @ www-widgetapi.js:536
Z @ www-widgetapi.js:567
init @ youtube.js:1
window.onYouTubeIframeAPIReady @ Fullscreen.js:44
(anonymous) @ www-widgetapi.js:590
(anonymous) @ www-widgetapi.js:590
module.js:202 MMM-GoogleAssistant is resumed.
www-embed-player.js:407 [Violation] 'setTimeout' handler took 393ms
lastScreenOutput.html?seed=1596404666078:74 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Ma @ lastScreenOutput.html?seed=1596404666078:74
T @ lastScreenOutput.html?seed=1596404666078:77
T.a @ lastScreenOutput.html?seed=1596404666078:78
(anonymous) @ lastScreenOutput.html?seed=1596404666078:80
[Violation] Forced reflow while executing JavaScript took 88ms
base.js:998 [Violation] 'setTimeout' handler took 75ms
module.js:195 MMM-GoogleAssistant is suspended.
module.js:202 MMM-GoogleAssistant is resumed.
lastScreenOutput.html?seed=1596404692222:74 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Ma @ lastScreenOutput.html?seed=1596404692222:74
T @ lastScreenOutput.html?seed=1596404692222:77
T.a @ lastScreenOutput.html?seed=1596404692222:78
x.registerHorizontalNavigationController @ lastScreenOutput.html?seed=1596404692222:78
h @ lastScreenOutput.html?seed=1596404692222:85
(anonymous) @ lastScreenOutput.html?seed=1596404692222:84
[Violation] Forced reflow while executing JavaScript took 96ms
main.js:288 Will not show MMM-Assistant2Display. LockStrings active: A2D_LOCKED
module.js:195 MMM-GoogleAssistant is suspended.
module.js:202 MMM-GoogleAssistant is resumed.
main.js:288 Will not show MMM-Assistant2Display. LockStrings active: GA_LOCKED
www-embed-player.js:763 [Violation] 'message' handler took 220ms
base.js:2947 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
addEventListener @ base.js:2947
g.ds.L @ base.js:5566
g.k.Nc @ base.js:6780
g.k.Nc @ base.js:7118
g.k.lf @ base.js:6777
(anonymous) @ base.js:998
g.k.S @ base.js:5493
g.k.S @ base.js:6607
g.k.KC @ base.js:7183
g.k.S @ base.js:5493
g.N.S @ base.js:5571
EK @ base.js:2877
GK @ base.js:2798
$T @ base.js:3605
g.k.playVideo @ base.js:7241
g.k.playVideo @ base.js:6478
VM.a.C.<computed> @ base.js:3016
g.k.handleExternalCall @ base.js:6453
X.a.u.<computed> @ base.js:3020
(anonymous) @ www-embed-player.js:717
n.ta @ www-embed-player.js:779
n.Va @ www-embed-player.js:768
Kj.m @ www-embed-player.js:764
lastScreenOutput.html?seed=1596404719297:74 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Ma @ lastScreenOutput.html?seed=1596404719297:74
T @ lastScreenOutput.html?seed=1596404719297:77
T.a @ lastScreenOutput.html?seed=1596404719297:78
(anonymous) @ lastScreenOutput.html?seed=1596404719297:80
[Violation] Forced reflow while executing JavaScript took 35ms
[Violation] Forced reflow while executing JavaScript took 84ms
youtube.js:1 [AMK2:ADDONS:A2D] Player Error 150: Not Allowed By Owner
main.js:288 Will not show MMM-Assistant2Display. LockStrings active: GA_LOCKED
module.js:195 MMM-GoogleAssistant is suspended.

I have a sneaking suspicion that this has a correlation with the fact that my address is set to 0.0.0.0, but changing that isn't really an option for me.

**Comment by yurMoThEr** [comment]
Any help is appreciated!

**Comment by bugsounet** [comment]
why duplicate [there](https://github.com/Anonym-tsk/MMM-YouTube/issues/12) ?

I repeat again... the same response: use `address: "localhost",`

So It's the YouTube API google rules. I can't do better
