### ISSUE TITLE
Spotify not playing

### ISSUE THREAD

**Issue by masoudl** [bugsounet/MMM-Assistant2Display#106]
Hi,

I am using RP3 with Google Voicehat kit. I have gotten MM2 w/ MMM-Assistant and A2D to work (I get Jarvis to respond with text as well as audio responses., and it plays YouTube as well.
However I am unable to get it to play spotify. I believe it has something to do with my configuration, and believe me I don't want to waste your time with little config problems, so I spent hours reading every line of MMM-Spotify, MMM-GoogleAssistant, and MMM-Assistant2Display wikis to figure out what I am missing, but so far all I get is to have Jarvis try and open Spotify (the icon reacts to spotify commands) but nothing plays. 
Again I am sure this is my mistake, but I would appreciate your help.
Symptoms: 
- Upon load Spotify icon appears momentarily in bottom left and then disappears
- When giving the command "Jarvis, Top Hits on Spotify", Jarvis reacts with a new icon, but nothing happens.

Here is what I have tried so far:
1- I have installed MMM-Spotify, and gotten client_ID and secret,
2- I added a recipe to MMM-GoogleAssistant <= Without this I wouldn't even get it to react to Spotify commands, instead in response to "Top hits on Spotify" Jarvis says "Sorry, I don't understand".
3- In MMM-Assustat2Display config, I have tried multiple true/false combinations for "useSpotify and useIntegred", and neithr work.
... The config section is below:
		{
			module: "MMM-Assistant2Display",
			position: "top_left",
			config: {
				debug:false,
				useYoutube:true,
				spotify: {
					useSpotify: true,
					useIntegred: false,
					useLibrespot: false,
					connectTo: null,
					playDelay: 3000,
					minVolume: 10,
					maxVolume: 100,
					updateInterval: 1000,
					idleInterval: 10000,
					username: "my username for Spotify",
					password: "my pwd for Spotify",
					CLIENT_ID: "client id supplied by Spotify for this app",
					CLIENT_SECRET: "client secret supplied by Spotify for this app",
					deviceDisplay: "Listening on",
					usePause: true
				},	
			},
...
Thank you for your help.

**Comment by bugsounet** [comment]
Hi, can you read the [spotify wiki part](https://github.com/bugsounet/MMM-Assistant2Display/wiki/spotify).
It's can help you to configure it

You actual configuration can't play anything ;)
