### ISSUE TITLE
Control spotify with voice

### ISSUE THREAD

**Issue by Beastlynoob** [bugsounet/MMM-Assistant2Display#107]
Thank you for creating such an amazing module I really appreciate it. Whenever I play something on Spotify and tell my assistant to skip the song or a command like that, it replies with sorry I don't understand. Did I miss something in the wiki?

**Comment by bugsounet** [comment]
Sorry, I return from vacations !
I don't update the spotify wiki...
now it's updated, I special recipe has been created

**Comment by Beastlynoob** [comment]
Sorry this issue isn't resolved yet, when I tell it to do Spotify next or something similar it will play a song called next or something similar. The voice commands no work.

**Comment by bugsounet** [comment]
do you load the recipe ?

**Comment by Beastlynoob** [comment]
What do you mean?

**Comment by bugsounet** [comment]
> Sorry, I return from vacations !
I don't update the spotify wiki...
now it's updated, I special recipe has been created

do you read new wiki of spotify part ?

**Comment by Beastlynoob** [comment]
Yes, you added common commands to use with Spotify to control with voice. I tried using the commands but they did not work.

**Comment by bugsounet** [comment]
> Yes, you added common commands to use with Spotify to control with voice. I tried using the commands but they did not work.

no... i don't add custom command but I do a recipe to load with MMM-GoogleAssistant
If you don't load it, i wiil not works

**Comment by Beastlynoob** [comment]
How do I load recipe? I no see on wiki
