### ISSUE TITLE
Hello I am using this well

### ISSUE THREAD

**Issue by sdlckdrl** [bugsounet/MMM-Assistant2Display#108]
If debug mode is not true, the screen will not turn off.

**Comment by bugsounet** [comment]
humm I think it's not possible ... just because it's display log or not
Debug mode never influence the main code (it's an Golden Rule)
In my Prod mirror, debug mode is not actived, there is no problem

So it's something else ?
what's your config ?

**Comment by bugsounet** [comment]
ok, so if you don't respond, I think that the problem is now solved
