### ISSUE TITLE
GooglePhotos Not Working

### ISSUE THREAD

**Issue by dhriti-krishna** [bugsounet/MMM-Assistant2Display#109]
Hey Cedric,

I just wanted to tell you that the Google Photos isn't working for me.
When I ask Jarvis to show me my Google Photos, Jarvis tells me that I don't have any "relevant" photos.

This is my config.js file:

{
		  module: "MMM-Assistant2Display",
		  position: "top_left",
		  config: {
		    debug:false,
		    useYoutube: true,
		    links: {
		      useLinks: false,
		      displayDelay: 60 * 1000,
		      scrollStep: 25,
		      scrollInterval: 1000,
		      scrollStart: 5000,
		      scrollActivate: false,
		      verbose: false
		    },
		    photos: {
		      usePhotos: true,
		      displayDelay: 10 * 1000
		    },
		    volume: {
		      useVolume: true,
		      volumePreset: "ALSA",
		      myScript: null
		    },
		    briefToday: {
		      useBriefToday: false,
		      welcome: "Brief Today"
		    },
		    screen: {
		      useScreen: false,
		      delay: 5 * 60 * 1000,
		      turnOffDisplay: true,
		      ecoMode: true,
		      displayCounter: true,
		      displayBar: false,
		      displayStyle: "Text",
		      text: "Auto Turn Off Screen:",
		      detectorSleeping: false,
		      governorSleeping: false,
		      rpi4: false
		    },
		    pir: {
		      usePir: false,
		      gpio: 21,
		      reverseValue: false
		    },
		    governor: {
		      useGovernor: false,
		      sleeping: "powersave",
		      working: "ondemand"
		    },
		    internet: {
		      useInternet: true,
		      displayPing: true,
		      delay: 2* 60 * 1000,
		      scan: "google.fr",
		      command: "pm2 restart 0",
		      showAlert: true
		    },
		    TelegramBot: {
		      useTelecastSound: false,
		      TelecastSound: "TelegramBot.ogg"
		    },
		    cast: {
		      useCast: true,
		      castName: "MagicMirror_A2D",
		      port: 8569
		    },
		    spotify: {
		      useSpotify: false,
		      useIntegred: false,
		      useLibrespot: false,
		      connectTo: "Librespot",
		      playDelay: 3000,
		      minVolume: 10,
		      maxVolume: 100,
		      updateInterval: 1000,
		      idleInterval: 10000,
		      username: "",
		      password: "",
		      CLIENT_ID: "",
		      CLIENT_SECRET: "",
		      deviceDisplay: "Listening on",
		      usePause: true
		    }
		  }
		},
Is there any solution for this?

**Comment by bugsounet** [comment]
Hi,
* are you sure there are some photos in your google account ?
* can you verify with your browser in google photos ?
* are you sure your photos is on the same account that your google assistant project ?

**Comment by dhriti-krishna** [comment]
1. Yes, there are photos in my google account.
2. Yes, I opened google photos and have 18 photos uploaded.
3. Yes, the photos and the assistant are in the same google account.

**Comment by dhriti-krishna** [comment]
Hi @bugsounet, do you have any solution for this issue? So to bother you 😬

**Comment by bugsounet** [comment]
what do try to say for display it ? (sometime google server react weird ...)

**Comment by dhriti-krishna** [comment]
I just say, "Jarvis, show me my pictures" or "Jarvis, show me my Google Pictures"

**Comment by lxne** [comment]
Is youtube working?
Did you try briefToday and was it working?

**Comment by dhriti-krishna** [comment]
Hi, youtube is working perfectly. 
I tried briefToday and the Google Photos were not working still.

**Comment by bugsounet** [comment]
Hi, ... i think to that ... **maybe** it can solve:

1) verify if Google Photos is intalled on your phone (and activated)
2) go to Google Home app on your phone
3) go to your icon account (upper right icon)
4) Google assistant parameter
5) services Tab
6) Video and photos
7) verify if google photo is activated and checked

**Comment by dhriti-krishna** [comment]
Hi @bugsounet, 
I checked followed your steps to find if the Google Photos was activated and it was.
The assistant still could not show me my Google Photos. 😕
Perhaps you could show me your configuration for the MMM-GoogleAssistant and MMM-Assistant2Display?
I'll see if I did anything wrong.
If there's nothing wrong with my configuration and the photos still don't work, I'll close the issue.

**Comment by bugsounet** [comment]
it's not GA or A2D issue ... it's Google issue, if google server don't want to send you your request ...
and if I don"t want, so i can do anything :'(

sorry i don't work at Google, so i have the hand of Google Server response :(

**Comment by dhriti-krishna** [comment]
Fine. I'm going to close this issue.
