### ISSUE TITLE
Google Assistant Returning Strange Results?

### ISSUE THREAD

**Issue by jmwyds** [bugsounet/MMM-Assistant2Display#110]
When I ask Google what the weather is, it returns a web search result and simply shows the link for where I could find the current weather. When I ask for humidity, it tells me the definition of humidity according to Weather.com. When I used to ask these questions Google Assistant would simply tell me the current weather or the current humidity. I'm not sure if something in my configuration is off, but I have provided my MMM-Assistant2Display and MMM-GoogleAssistant configs below.

`{
		  module: "MMM-Assistant2Display",
		  position: "top_left",
		  config: {
			debug:false,
			useYoutube: true,
			photos: {
			  usePhotos: true,
			  displayDelay: 10 * 1000
			},
			volume: {
			  useVolume: true,
			  volumePreset: "ALSA",
			  myScript: null
			},
			screen: {
			  useScreen: true,
			  delay: 5 * 60 * 1000,
			  turnOffDisplay: true,
			  ecoMode: true,
			  displayCounter: true,
			  displayBar: false,
			  displayStyle: "Text",
			  text: "Auto Turn Off Screen:",
			  detectorSleeping: false,
			  rpi4: false
			},
			pir: {
			  usePir: true,
			  gpio: 4,
			  reverseValue: false
			},
			internet: {
			  useInternet: true,
			  displayPing: false,
			  delay: 2* 60 * 1000,
			  scan: "google.fr",
			  command: "pm2 restart 0",
			  showAlert: true
			},
			TelegramBot: {
			  useTelecastSound: false,
			  TelecastSound: "TelegramBot.ogg"
			},
			cast: {
			  useCast: false,
			  castName: "MagicMirror_A2D",
			  port: 8569
			}
		  }
		},`

`{
		  module: "MMM-GoogleAssistant",
		  position: "fullscreen_above",
		  config: {
			debug: false,
			assistantConfig: {
			  lang: "en-US",
			  projectId: "", // Required to use gaction.
			  modelId: "", // (OPTIONAL for gaction)
			  instanceId: "", // (OPTIONAL for gaction)
			  latitude: 42.7351,
			  longitude: 87.4193
			},
			responseConfig: {
			  useScreenOutput: true,
			  screenOutputCSS: "screen_output.css",
			  screenOutputTimer: 5000,
			  activateDelay: 250,
			  useAudioOutput: true,
			  useChime: true,
			  newChime: false,
			  useNative: true,
			  playProgram: "mpg321"
			},
			micConfig: {
				recorder: "arecord",
				device: "plughw:1"
			},
			customActionConfig: {
			  autoMakeAction: false,
			  autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
			  actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
			},
			snowboy: {
			  audioGain: 2.0,
			  Frontend: true,
			  Model: "jarvis",
			  Sensitivity: 0.7
			},
			A2DServer: {
			  useA2D: true,
			  stopCommand: "stop"
			},
			recipes: [ "with-MMM-TelegramBot.js", "Reboot-Restart-Shutdown.js", "with-MMM-TelegramBot.js" ]
		  }
		},`

**Comment by bugsounet** [comment]
unfortunately, I cannot change the responses that google gives :(
it's probably temporary, I think
I already had your case, some time ago and it started again afterwards.
possibly while waiting for a return to normal from the google server, you can activate the reading of the links result in A2D config (see wiki)

I also remind you that Gogole SDK is +/- a demo of a real google assistant ... with his bug and his news
and I have to adapt with their answer (I have no control over it)

just wait and see ...

**Comment by jmwyds** [comment]
Okay, thanks Cedric. I appreciate the quick response. I just wanted to make sure I hadn't messed something up in my configs. Thanks!
