### ISSUE TITLE
PIR sensor wont activate

### ISSUE THREAD

**Issue by lyonrt** [bugsounet/MMM-Assistant2Display#112]
What could I be missing for the PIR to not activate?  I have it on pin 1,3, and 8 on the right side so GPIO is at 23.

I tried alternating the reverse value with no luck as well.

Kind Regards,

Tyler 

module: "MMM-Assistant2Display",
  position: "top_left",
  config: {
    debug:false,
    useYoutube: true,
    links: {
      useLinks: false,
      displayDelay: 60 * 1000,
      scrollStep: 25,
      scrollInterval: 1000,
      scrollStart: 5000,
      scrollActivate: false,
      verbose: false
    },
    photos: {
      usePhotos: false,
      displayDelay: 10 * 1000
    },
    volume: {
      useVolume: true,
      volumePreset: "ALSA",
      myScript: null
    },
    briefToday: {
      useBriefToday: false,
      welcome: "brief Today"
    },
    screen: {
      useScreen: true,
      delay: 5 * 60 * 1000,
      turnOffDisplay: true,
      ecoMode: true,
      displayCounter: true,
      displayBar: false,
      displayStyle: "Text",
      text: "Auto Turn Off Screen:",
      detectorSleeping: true,
      governorSleeping: false,
      displayLastPresence: true,
      LastPresenceText: "Last Presence:",
      rpi4: false
    },
    pir: {
      usePir: true,
      gpio: 23,
      reverseValue: false
    },
    governor: {
      useGovernor: true,
      sleeping: "powersave",
      working: "ondemand"
    },
    internet: {
      useInternet: false,
      displayPing: false,
      delay: 2* 60 * 1000,
      scan: "google.fr",
      command: "pm2 restart 0",
      showAlert: true
    },
    TelegramBot: {
      useTelecastSound: false,
      TelecastSound: "TelegramBot.ogg"
    },
    cast: {
      useCast: true,
      castName: "MagicMirror_A2D",
      port: 8569
    },
    spotify: {
      useSpotify: false,
      useIntegred: false,
      useLibrespot: false,
      connectTo: null,
      playDelay: 3000,
      minVolume: 10,
      maxVolume: 100,
      updateInterval: 1000,
      idleInterval: 10000,
      username: "",
      password: "",
      CLIENT_ID: "",
      CLIENT_SECRET: "",
      deviceDisplay: "Listening on",
      usePause: true
    }
  }

**Comment by lxne** [comment]
Hi, as far as I see there is no problem with the config.
Did you test your PIR sensor?
https://tutorials-raspberrypi.com/connect-and-control-raspberry-pi-motion-detector-pir/

**Comment by bugsounet** [comment]
I have do an tutorial in the forum but it's in french.
I think i will do a wiki part for this ;)

**Comment by RIKKO14** [comment]
and this tutorial is great !!
I was able to adjust my PIR and it works very well, thank you again bugsounet !!!

**Comment by bugsounet** [comment]
thx !
I write it on [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki/pir#how-do-some-simply-test-and-setup-sensibilitydelay-of-your-pir-sensor-)

**Comment by bugsounet** [comment]
Hi, no response from author, i think problem is now solved
