### ISSUE TITLE
doubler la taille de la barre spotify

### ISSUE THREAD

**Issue by bigjojo** [bugsounet/MMM-Assistant2Display#116]
bonjour bougsounet,
d'abort bravo pour ce module très complet.
j'aimerai savoir si il y a possibilité de doubler la taille de la barre spotify, je la trouve un peu petite.
merci d'avance.

**Comment by bugsounet** [comment]
bonjour,

c'est à vous de modifier le css, le fichier est `screen.css` ;)
la partie css de spotify est taggé et démarre [ici](https://github.com/bugsounet/MMM-Assistant2Display/blob/prod/screen.css#L71)

**Comment by bigjojo** [comment]
bonjour et merci.
je vais regardé de plus près ce fichier.
bonne journée.
