### ISSUE TITLE
MMM-bugsounet raspi 4 ?

### ISSUE THREAD

**Issue by sansamy** [bugsounet/MMM-Assistant2Display#123]
Bonjour, tout d abord merci pour votre travail .
Vos modules assistant2display et GA sont ils compatibles avec raspi pi 4 car youtube est saccadé avec mon pi3b+ aussi si ça marche vous me conseille la version 4gigas ou nécessite la 8 gigas? Merci

**Comment by bugsounet** [comment]
Hi
personnaly, i start with rpi 3b+ and you have right but really better with openGL activation
I upgraded with RPI4 2Gb, and works without lag (YouTube, FreeboxTV, Cast, ...) and very fluid.
I use governor powersave for sleep and wakeup is 2 sec ( so not instantaneous) but it's my choice for RPI save :)

After RPI4 4Gb or 8Gb why not ... but remember not using 64bits Os :)
All Program, like MM and each modules are on 32bits system

**Comment by sansamy** [comment]
Merci pour la réponse rapide, je vais faire ça en 2 go alors si YouTube est fluide ca me va

**Comment by sansamy** [comment]
Aussi pour laisser en 32 bits si je met ma carte sd du rpi3 dans le rpi 4 ca va ? Ou je dois télécharger une version spéciale de raspian ou mm pour que ça reste en 32? Merci

**Comment by bugsounet** [comment]
[la version offciel](https://www.raspberrypi.org/downloads/raspberry-pi-os/): `Raspberry Pi OS (32-bit) with desktop` suffira

Tiens j'ecris en françois moi !? :)

**Comment by sansamy** [comment]
Lol same for me 😁thank u alors

**Comment by sansamy** [comment]
That translate automatic i think

**Comment by bugsounet** [comment]
no :)
it's not automatic ... I works with many english person so .. it's help for learning english :)
my bad english is not perfect !!

have a nice day !
@bugsounet

**Comment by sansamy** [comment]
Good initiative , my english is also no so good i do max in english.
