### ISSUE TITLE
wake up and sleep

### ISSUE THREAD

**Issue by lyonrt** [bugsounet/MMM-Assistant2Display#127]
Just realized my PIR sensor is bad,  but reading the notes it says I can use without?

How would i configure it to wake up using "Jarvis" and " go to sleep" using Jarvis?

Thx,

Tyler

**Comment by bugsounet** [comment]
I have done a recipe for turn on/off screen

look at recipes directory `ScreenManager.js` and rename the script and change `pattern` into your language
of course load it in `recipes []` in your module configuration
