### ISSUE TITLE
-Solved - Current Issues ! (YouTube and Spotify). Thanks to read before open an issue

### ISSUE THREAD

**Issue by bugsounet** [bugsounet/MMM-Assistant2Display#129]
There is some change in Google Server (I just discouvert it and i'm suprised !)

So MMM-GoogleAssistant not send Correctly the callback for playing YouTube Video and Spotify music

Why ?
Google Assistant read Google Server response to send to Assistant2Display and if google make some change...
it's break the code

I will try to fix it Soon as possible !

**Comment by mrandrian** [comment]
You did your best

**Comment by bugsounet** [comment]
YouTube And Spotify is now ok

Read Wiki for more informations !

**Comment by mrandrian** [comment]
After update MMM-GoogleAssistant and MMM-Assistant2Display. I tried YouTube and it still doesn't work.

**Comment by bugsounet** [comment]
> I tried YouTube and it still doesn't work.

you have installed Youtube API ?

**Comment by mrandrian** [comment]
Sure, i had installed YouTube Api and enabled it on my cloud project

**Comment by bugsounet** [comment]
`useYouTube: true` in A2DServer of GA ?

**Comment by mrandrian** [comment]
Yess.. as default. useYouTube : true

**Comment by mrandrian** [comment]
> `useYouTube: true` in A2DServer of GA ?

Ooyaaaa. Its my bad. I only apply that on A2D config. Not in GA. I will try

**Comment by bugsounet** [comment]
it's horrible when there are changes on the google server ... a lot of influence for you (a lot of configuration) and for me (a lot of coding ...)

**Comment by mrandrian** [comment]
> `useYouTube: true` in A2DServer of GA ?

I put that script in ADServer of GA. Now i had a warning, say "[ERROR] YouTube Search not Set!"

**Comment by bugsounet** [comment]
wiki [says](https://github.com/bugsounet/MMM-Assistant2Display/wiki/YouTube#errors), you have this error if the token is not created

**Comment by sshbird** [comment]
[2020-09-28 21:29:56.285] [LOG]    [A2D] Assistant2Display is initialized.
[2020-09-28 21:29:56.287] [LOG]    [ASSISTANT] MMM-GoogleAssistant Version: 2.4.13
[2020-09-28 21:29:56.290] [LOG]    [ASSISTANT] YouTube Search Function initilized.

I updated  MMM-GoogleAssistant and Assistant2Display and make tokenYT.json as it is said on WiKi
but GA does not auto launch Youtube play
is there anything i can check ?

**Comment by bugsounet** [comment]
and what do you say for search a video ?

**Comment by sshbird** [comment]
> and what do you say for search a video ?

i said jarvis youtube [singer name]

**Comment by bugsounet** [comment]
this [part](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration#magicmirror-configuration) is ok ?

**Comment by sshbird** [comment]
> this [part](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration#magicmirror-configuration) is ok ?

this is my config.js related to that part

var config = {
        address: "localhost",   // Address to listen on, can be:
                                                        // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
                                                        // - another specific IPv4/6 to listen on a specific interface
                                                        // - "0.0.0.0", "::" to listen on any interface
                                                        // Default, when address config is left out or empty, is "localhost"
        port: 9999,
        electronOptions: {
           webPreferences: {
               webviewTag: true
         }
        },

**Comment by mrandrian** [comment]
> wiki [says](https://github.com/bugsounet/MMM-Assistant2Display/wiki/YouTube#errors), you have this error if the token is not created

Of course i missed this one. Now everything is going as it should. Thks

**Comment by sshbird** [comment]
> > this [part](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration#magicmirror-configuration) is ok ?
> 
> this is my config.js related to that part
> 
> var config = {
> address: "localhost", // Address to listen on, can be:
> // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
> // - another specific IPv4/6 to listen on a specific interface
> // - "0.0.0.0", "::" to listen on any interface
> // Default, when address config is left out or empty, is "localhost"
> port: 9999,
> electronOptions: {
> webPreferences: {
> webviewTag: true
> }
> },
> 
> Thank for your support, but it does not work

i found the problem
i changed lang:"ko-KR" to "en-US" and it worked

{
  module: "MMM-GoogleAssistant",
  position: "fullscreen_above",
  config: {
    debug:true,
    assistantConfig: {
      lang: "en-US",
      projectId: "", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)

is it caused from UTF encoding issue when international language youtube search word is delivered to youtube API?

**Comment by bugsounet** [comment]
it's possible, sorry, i can't do any test with this language

**Comment by sshbird** [comment]
> it's possible, sorry, i can't do any test with this language

thank you for the quick reply , anyway, i'm really a big fan of your modules, cheers!!
