### ISSUE TITLE
usePIR, but countdown is not working

### ISSUE THREAD

**Issue by JSLEE0413** [bugsounet/MMM-Assistant2Display#13]
screen: {
      useScreen: true,
      delay:  1 * 10 * 1000,
      turnOffDisplay: true,
      ecoMode: false,
      displayCounter: true,
      text: "Auto Turn Off Screen: ",
      detectorSleeping: true,
      governorSleeping: false,
      rpi4: true
    },
    pir: {
      usePir: true,
      gpio: 6,
      reverseValue: false
    },

this is my config.js
i've already checked my sensor is working. and my pi is rpi4, so i set true on rpi4.

anyway, countdown does not working. only "Auto Turn Off Screen: --:--:--"  

anything wrong with my config?

also screen is not turning off after 10 seconds,

**Comment by bugsounet** [comment]
do you set `useA2D: true` in your MMM-AssistantMk2 config ?

**Comment by JSLEE0413** [comment]
i just set it and it works on ecoMode.

but MMM-CalenderExt2 with MMM-pages appears in ecoMode.

is there any way to turn the monitor off instead of fade out?


set ecoMode: false is just countdown, without turn off display.

**Comment by bugsounet** [comment]
Hi, some user reports to me, with RPI4, `turnOffDisplay` feature works with `rpi4: false`
It's depend of rpi4 firmware, with lastest it's works now

@hweigel says : 
> For those Raspberry Pi 4 users affected, try updating the operating system **including** its firmware and kernel:
> 
> ```sh
> sudo apt-get update
> sudo apt-get dist-upgrade
> sudo reboot
> sudo rpi-update
> sudo reboot
> ```

**Comment by JSLEE0413** [comment]
it works now. thank you so much. :)

**Comment by lxne** [comment]
> i just set it and it works on ecoMode.
> 
> set ecoMode: false is just countdown, without turn off display.

I do have this issue on my rip 3b+.
Display is only turning off if ecoMode is true.
With the settings below countdown counts to 0 but screen does not turn off.
If something moves countdown starts anew.

Do I misunderstand ecoMode?

Installed everything form scratch without errors.
Hardware: rpi 3b+, ReSpeaker 2-mic hat, Grove Gesture Sensor, Grove PIR Motion Sensor
System: Buster, MagicMirror 2.11.0, MMM-GoogleAssistant & MMM-Assistant2Display

screen: settings
 ```
                               screen: {
                                        useScreen: true,
                                        delay: 1 * 60 * 1000,
                                        turnOffDisplay: true,
                                        ecoMode: false,
                                        displayCounter: true,
                                        text: "Auto Turn Off Screen:",
                                        displayBar: true,
                                        displayStyle: "Text",
                                        detectorSleeping: true,
                                        governorSleeping: false,
                                        rpi4: false
                                },
```
