### ISSUE TITLE
Google assistant won't listen to what i say. It just says. I Sorry, i dont understand.

### ISSUE THREAD

**Issue by jorickjuh** [bugsounet/MMM-Assistant2Display#133]
Google assistant won't listen to what i say. It just says. I Sorry, i dont understand. But i can active google with the hotword Ok google. Or Hey google.

Any ideas why? When i use npm start. it wont show any error. So idk

**Comment by jorickjuh** [comment]
![image](https://user-images.githubusercontent.com/26413543/95126870-6439f080-0757-11eb-841c-aa2e80d054c0.png)

**Comment by bugsounet** [comment]
in all case it's not an A2D issue, Please open it on the proper module thx
