### ISSUE TITLE
blank screen when adding the A2D module

### ISSUE THREAD

**Issue by bravozulu1979** [bugsounet/MMM-Assistant2Display#134]
Everything works fine including Jarvis wake up, until I add the A2D module. Once I add it, Magic Mirror only goes to a completely black screen. A2D installed without any problems.

**Comment by lxne** [comment]
Did you do any 'npm audit fix'?

**Comment by bravozulu1979** [comment]
I did .. there were 6 high severity vulnerabilities. 

when I run npm audit.. here's a response I get -

 === npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution in node-forge                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-forge                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.10.0                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-ga                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-ga > @bugsounet/google-assistant >         │
│               │ google-auth-library > gtoken > google-p12-pem > node-forge   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1561                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 308 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by bugsounet** [comment]
so ... I say `bravo`...

**Comment by bravozulu1979** [comment]
> so ... I say `bravo`...

and anything to help with the blackscreen ?

**Comment by bugsounet** [comment]
humm... reassure me, when you have a breakdown at your place ... you will not go to inspect the neighbor's?

**Comment by lxne** [comment]
Wiki says: Don't do any other npm...
The problem is also discussed in the closed issues.

Tip: "retry with 'npm run rebuild' in GA directory and don't do another npm commands after installation."

**Comment by bravozulu1979** [comment]
Sir .. I am a novice user here.. am I doing something wrong? what do you
mean by breakdown? Am I leaving something really vulnerable here?

**Comment by bravozulu1979** [comment]
Sorry, I missed that. What’s the GA directory? (Apologies for the stupid
question)

**Comment by lxne** [comment]
GoogleAssistant

**Comment by bugsounet** [comment]
GA= GoogleAssiant
A2D= Assistant2Display

**Comment by bugsounet** [comment]
So why do you use GoogleAssistant Directory ? [that why my neighbor example !]

If you have a problem with A2D... it's on A2D directory or it's on config.js file

Are there an error on npm start ? (I don't have to ask you... You have to send me all information)

**Comment by bravozulu1979** [comment]
> Wiki says: Don't do any other npm...
> The problem is also discussed in the GA's closed issues.
> 
> Tip: "retry with 'npm run rebuild' in GA directory and don't do another npm commands after installation."

I did the npm run rebuild .. in GA directory and NO other npm commands. GA was successfully installed again. Still the same problem.

**Comment by bugsounet** [comment]
So i don't understand your issue ... It's a GoogleAssiant Issue or Assistant2display issue ?

**Comment by lxne** [comment]
Deactivate A2D in config to check if MM works without it.

```
				A2DServer: {
					useA2D: false,
```
```
			module: "MMM-Assistant2Display",
			disabled: true,
```

**Comment by bravozulu1979** [comment]
GA works perfectly. It's the A2D that I have a problem with. Commented out A2D in the config file and GA works alright. I am going to do a npm run rebuild in the A2D directory and let you know the results.

**Comment by bravozulu1979** [comment]
npm run rebuild in A2D seems to have worked. I don't get the black screen anymore. Now I need to test A2D.

**Comment by bravozulu1979** [comment]
tested Youtube and it works very well. Thank you, I am closing the issue.
