### ISSUE TITLE
A2D doesnt work (is disabled

### ISSUE THREAD

**Issue by JTprogramm** [bugsounet/MMM-Assistant2Display#135]
Hello together,

unfortunaly  A2S appearently doesnt work on my RPI 3B+.

When I installed it and do first configurations in the config.js everthing seems fine. But when I try to cast a Youtubevideo by my Youtube-App I can't find the device in the castlist. After then I prepared the Youtube and Spotify. Again no problems during Installation and configuration. But when I say "Youtube ..." or "... on Spotify" there is only the normal response of GA as shown  in the screenshots. 
![Spotify_Play](https://user-images.githubusercontent.com/32705356/95888598-919f2380-0d81-11eb-8c9f-a5c64d26f0a2.jpg)
![Youtube](https://user-images.githubusercontent.com/32705356/95888600-92d05080-0d81-11eb-9773-92855a180da1.jpg)
![Spotify](https://user-images.githubusercontent.com/32705356/95888601-9368e700-0d81-11eb-8281-852246e12b28.jpg)

**It apears only the Google Assistant but not the A2D work/response.**
I check my config.js more than twice, but inside of it everthings seems fine and the modules are in the right dependency.

#############################################################################################
`
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	electronOptions: {
			webPreferences: {
				webviewTag: true
			}
	},
	port: 8080,
	ipWhitelist: [], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "de",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
       			 module: 'MMM-pages',
       			 config: {
               			 modules:
                   			 [["MMM-AfterShip","MMM-Fuel","MMM-COVID19"],
                    			 [ "MMM-EmbedYoutube"]],
               			 fixed: ["MMM-GoogleAssistant","clock", "currentweather",
					"alert","updatenotification","calendar",'MMM-MicrosoftToDo',
					"MMM-OpenmapWeather","weatherforecast",'MMM-Screencast',
					"newsfeed","MMM-page-indicator"],
        			}
    		},
		/*{

   		 module: "MMM-Wallpaper",

   		 position: "fullscreen_below",

   		 config: { // See "Configuration options" for more information.

     		 source: ["bing","chromecast","firetv"],

     		 slideInterval: 60 * 1000 // Change slides every minute

    			}

 		 },*/
		{
  			module: "MMM-GoogleAssistant",
  			position: "top_bar",
  			config: {
    				assistantConfig: {
					lang: "de-DE",
      					projectId: "magicmirrorassistant-869cc", // Required to use gaction.
      					modelId: "***********************************************", // (OPTIONAL for gaction)
      					//instanceId: "", // (OPTIONAL for gaction)
      					latitude: ********,
      					longitude: **************,
   						 },
				responseConfig: {
      					useScreenOutput: true,
      					screenOutputCSS: "screen_output.css",
      					screenOutputTimer: 5000,
      					screenRotate: false,
      					activateDelay: 250,
      					useAudioOutput: true,
      					useChime: true,
      					newChime: false,
      					useNative: false,
      					playProgram: "mpg321"
    					},
    				micConfig: { // put there configuration generated by auto-installer
      					recorder: "arecord",
     		 			device: "plughw:2",
    				},
				customActionConfig: {
  					autoMakeAction: true,
  					autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
  					actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
				},
				recipes: [ "test.js","Reboot-Restart-Shutdown.js", "with-A2DSpotify.js" ],
  				},
				A2DServer: {
					useA2D: true,
					useYouTube: true,
					displayResponse: true
			},
		},
		{
			module: "MMM-Assistant2Display",
			position: "top_left",
			config: {
				debug:false,
				useYoutube: true,
				links: {
					useLinks: true,
					displayDelay: 60 * 1000,
					scrollStep: 25,
					scrollInterval: 1000,
					scrollStart: 5000,
					scrollActivate: false,
					verbose: false
				},
				photos: {
					usePhotos: false,
					displayDelay: 10 * 1000
				},
				volume: {
					useVolume: false,
					volumePreset: "ALSA",
					myScript: null
				},
				briefToday: {
					useBriefToday: true,
					welcome: "Guten Morgen"
				},
				screen: {
					useScreen: true,
					delay: 5 * 60 * 1000,
					turnOffDisplay: true,
					ecoMode: true,
					displayCounter: true,
					displayBar: false,
					displayStyle: "Text",
					text: "Auto Turn Off Screen:",
					detectorSleeping: false,
					governorSleeping: false,
					displayLastPresence: true,
					LastPresenceText: "Last Presence:",
					rpi4: false
				},
				pir: {
					usePir: false,
					gpio: 21,
					reverseValue: false
				},
				governor: {
					useGovernor: false,
					sleeping: "powersave",
					working: "ondemand"
				},
				internet: {
					useInternet: false,
					displayPing: false,
					delay: 2* 60 * 1000,
					scan: "google.fr",
					command: "pm2 restart 0",
					showAlert: true
				},
				cast: {
					useCast: true,
					castName: "MagicMirror_Cast",
					port: 8569,
				},
				spotify: {
					useSpotify: true,
					useIntegred: true,
					useLibrespot: true,
					connectTo: "MirrorSpeaker",
					playDelay: 3000,
					minVolume: 10,
					maxVolume: 100,
					updateInterval: 1000,
					idleInterval: 10000,
					username: "***********",
					password: "************",
					CLIENT_ID: "*************************",
					CLIENT_SECRET: "***************************",
					deviceDisplay: "Listening on",
					usePause: true,
					typeArtist: "artist",
					typePlaylist: "playlist",
					typeAlbum: "album",
					typeTrack: "track"
				},
				NPMCheck: {
					useChecker: true,
					delay: 10 * 60 * 1000,
					useAlert: true
				}
			}
		},
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Mein Kalendar",
			position: "top_left",
			config: {
				calendars: [
					{	
						maximumNumberOfDays: 7,
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/*********************/*******************************************/basic.ics"					}
				]
			}
		},
{
    module: 'MMM-MicrosoftToDo',
    position: 'top_left',	// This can be any of the regions. Best results in left or right regions.
    header: 'Meine ToDos', // This is optional
    config: {
      oauth2ClientSecret: '***************************',
      oauth2RefreshToken: '***********************************************************************************************************************************************************************************************************************************************************',
      oauth2ClientId: '*************************************************************',
      //listName: "" , // optional parameter: if not specified displays tasks from default "Tasks" list, if specified will look for a task list with the specified name (exact spelling)
      //listId: , // deprecated parameter: use listName instead
      showCheckbox: true, // optional parameter: default value is true and will show a checkbox before each todo list item
      showDueDate: true, // optional parameter: default value is false and will show the todo list items due date if it exists on the todo list item
      dateFormat: 'ddd MMM Do [ - ]', //optional parameter: uses moment date format and the default value is 'ddd MMM Do [ - ]'
      hideIfEmpty: false, // optional parameter: default value is false and will show the module also when the todo list is empty
      maxWidth: 450, // optional parameter: max width in pixel, default value is 450
      itemLimit: 200, // optional parameter: limit on the number of items to show from the list, default value is 200
      orderBy: 'subject', // optional parameter: 'subject' - order results by subject/name, 'dueDate' - order results by due date, default value is unordered
      completeOnClick: true, // optional parameter: default value is false, when set to true complete task when clicking on it
    }
  },
{
    disabled: false,
    module: "MMM-AfterShip",
    position: "top_left",
    config: {
        apiKey: "*************************************",  // Your free API Key from aftership.com
        apiLanguage: "de",
        useHeader: true,                   // False if you don't want a header      
        header: "Meine Sendungen",      // Change in config file. useHeader must be true
        maxWidth: "300px",
        animationSpeed: 3000,              // fade speed
        rotateInterval: 30 * 1000,         // seconds between shipments
        dateTimeFormat: "ddd, MMM DD, YYYY, h:mm a",
        dateFormat: "ddd, MMM DD, YYYY"
    }
},
   {
    disabled: true,
    module: 'MMM-ISS-Live',
    position: 'top_left',
    config: {
    	useHeader: false,                // true if you want a header
    	header: "",                      // Change in config file. useHeader must be true
    	animationSpeed: 1000,            // fade speed
}
},
	//	{	disabled: true
	//		module: "compliments",
	//		position: "lower_third"
	//	},
		{
            module: "MMM-OpenmapWeather",
            position: "top_right",    // This can be any of the regions.
                                    // Best results in left or right regions.
        config: {
            // See 'Configuration options' for more information.
            location: "****************",
            locationID: "**********", //Location ID from http://openweathermap.org/help/city_list.txt
            appid: "*******************",  //openweathermap.org API key
                  colorIcon: true
            }
        },
        {
            module: "weatherforecast",
            position: "top_right",
            header: "Wettervorhersage für",
            config: {
                location: "*********",
                locationID: "*********",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
                appid: "**********************************
            }
        },
        {
        module: "MMM-Fuel",
        position: "top_right",
        config: {
        	api_key: "***********",
        	lat: *********,
        	lng: **************,
        	types: ["e5"],
        	// all your config options, which are different than their default values
    }
},

/*{
		module: 'iFrame',
		position: 'lower_third',	// This can be any of the regions.
		config: {
			// See 'Configuration options' for more information.
				url: "https://www.ardmediathek.de/tagesschau24/video/tagesschau-livestream/tagesschau24-livestream/tagesschau24/Y3JpZDovL2Rhc2Vyc3RlLmRlL3RhZ2Vzc2NoYXUvbGl2ZXN0cmVhbQ/",
				//url: "http://localhost/tagesschau24",
				width: "100%", // Optional. Default: 100%,
				height: "400px", //Optional. Default: 100px
			}
		},*/
	{
		module: "MMM-EmbedYoutube", // Path to youtube module from modules folder Exmaple: MagicMirror/modules/custom/MMM-EmbedYoutube/ so it's custom/MMM-EmbedYoutube
		position: "lower_third",	// This can be any of the regions.
		config: {
			// See 'Configuration options' in README.md for more information.
			//video_id: "w3jLJU7DT5E",
			playlist: "******************************************",
			loop: true,
			autoplay: false,
			color: "white",
			controls: true,
			fs: false,
			modestbranding: false
		}
	},
	{
    		module: "MMM-COVID19",
    		position: "lower_third",
    		config: {
      			updateInterval: 300000,
      			worldStats: true,
      			delta: true,
      			lastUpdateInfo: true,
      			countries: [ "Germany", "USA", "China", "Italy", "French" ],
      			headerRowClass: "small",
      			infoRowClass: "small",
      			rapidapiKey : "**********************************************",
      			highlightCountry : "Germany"
   	 }
  },

		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{	title: "BBC-News",
						url: "http://feeds.bbci.co.uk/news/video_and_audio/world/rss.xml"
					}
					,
					{
						title: "ARD-Nachrichten",
						url: "http://www.tagesschau.de/xml/rss2"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				showDescription: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`
#############################################################################################

According to some another Isussereports I try  "npm start" in the "MagicMirror"-Dependency to see the output and found some suspicius Log "[2020-10-13 18:07:16.242] [LOG]    [A2D] Assistant2Display is disabled.",

Output:
#############################################################################################
`pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.13.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2020-10-13 18:06:53.593] [LOG]    Starting MagicMirror: v2.13.0
[2020-10-13 18:06:53.635] [LOG]    Loading config ...
[2020-10-13 18:06:53.658] [LOG]    Loading module helpers ...
[2020-10-13 18:06:53.664] [LOG]    No helper found for module: MMM-pages.
[2020-10-13 18:07:02.313] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:02.315] [LOG]    Module helper loaded: MMM-GoogleAssistant
[2020-10-13 18:07:06.297] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:06.298] [LOG]    Module helper loaded: MMM-Assistant2Display
[2020-10-13 18:07:06.303] [LOG]    No helper found for module: alert.
[2020-10-13 18:07:06.426] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:06.427] [LOG]    Module helper loaded: updatenotification
[2020-10-13 18:07:06.429] [LOG]    No helper found for module: clock.
[2020-10-13 18:07:07.631] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:07.633] [LOG]    Module helper loaded: calendar
[2020-10-13 18:07:07.657] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:07.659] [LOG]    Module helper loaded: MMM-MicrosoftToDo
[2020-10-13 18:07:07.672] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:07.674] [LOG]    Module helper loaded: MMM-AfterShip
[2020-10-13 18:07:07.679] [LOG]    No helper found for module: MMM-OpenmapWeather.
[2020-10-13 18:07:07.681] [LOG]    No helper found for module: weatherforecast.
[2020-10-13 18:07:07.915] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:07.916] [LOG]    Module helper loaded: MMM-Fuel
[2020-10-13 18:07:07.918] [LOG]    No helper found for module: MMM-EmbedYoutube.
[2020-10-13 18:07:07.930] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:07.931] [LOG]    Module helper loaded: MMM-COVID19
[2020-10-13 18:07:08.014] [LOG]    Initializing new module helper ...
[2020-10-13 18:07:08.015] [LOG]    Module helper loaded: newsfeed
[2020-10-13 18:07:08.016] [LOG]    All module helpers loaded.
[2020-10-13 18:07:08.388] [LOG]    Starting server on port 8080 ...
[2020-10-13 18:07:08.397] [INFO]   You're using a full whitelist configuration to allow for all IPs
[2020-10-13 18:07:08.410] [LOG]    Server started ...
[2020-10-13 18:07:08.413] [LOG]    Connecting socket for: MMM-GoogleAssistant
[2020-10-13 18:07:08.415] [LOG]    Connecting socket for: MMM-Assistant2Display
[2020-10-13 18:07:08.416] [LOG]    Connecting socket for: updatenotification
[2020-10-13 18:07:08.418] [LOG]    Connecting socket for: calendar
[2020-10-13 18:07:08.419] [LOG]    Starting node helper for: calendar
[2020-10-13 18:07:08.421] [LOG]    Connecting socket for: MMM-MicrosoftToDo
[2020-10-13 18:07:08.422] [LOG]    MMM-MicrosoftToDo helper started ...
[2020-10-13 18:07:08.424] [LOG]    Connecting socket for: MMM-AfterShip
[2020-10-13 18:07:08.426] [LOG]    Starting node_helper for: MMM-AfterShip
[2020-10-13 18:07:08.428] [LOG]    Connecting socket for: MMM-Fuel
[2020-10-13 18:07:08.430] [LOG]    Starting module helper: MMM-Fuel
[2020-10-13 18:07:08.431] [LOG]    Connecting socket for: MMM-COVID19
[2020-10-13 18:07:08.432] [LOG]    Starting node helper for: MMM-COVID19
[2020-10-13 18:07:08.434] [LOG]    Connecting socket for: newsfeed
[2020-10-13 18:07:08.435] [LOG]    Starting node helper for: newsfeed
[2020-10-13 18:07:08.436] [LOG]    Sockets connected & modules started ...
[2020-10-13 18:07:09.113] [LOG]    Launching application.
[2020-10-13 18:07:15.358] [LOG]    Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/*********************************/****************************/basic.ics - Interval: 300000
[2020-10-13 18:07:15.675] [LOG]    Create new news fetcher for url: http://feeds.bbci.co.uk/news/video_and_audio/world/rss.xml - Interval: 300000
[2020-10-13 18:07:15.841] [LOG]    Create new news fetcher for url: http://www.tagesschau.de/xml/rss2 - Interval: 300000
[2020-10-13 18:07:15.857] [LOG]    [ASSISTANT] MMM-GoogleAssistant Version: 2.4.13
[2020-10-13 18:07:15.864] [LOG]    [SNOWBOY] Model selected: jarvis
[2020-10-13 18:07:15.922] [LOG]    [ASSISTANT] RECIPE_LOADED: test.js
[2020-10-13 18:07:15.931] [LOG]    [ASSISTANT] RECIPE_LOADED: Reboot-Restart-Shutdown.js
[2020-10-13 18:07:15.937] [LOG]    [ASSISTANT] RECIPE_LOADED: with-A2DSpotify.js
[2020-10-13 18:07:15.942] [LOG]    [NPM] Initialized v0.9.9
[2020-10-13 18:07:16.229] [LOG]    [ASSISTANT] Google Assistant is initialized.
[2020-10-13 18:07:16.240] [LOG]    [A2D] MMM-Assistant2Display Version: 2.3.17
**[2020-10-13 18:07:16.242] [LOG]    [A2D] Assistant2Display is disabled.**
[2020-10-13 18:07:16.251] [INFO]   Checking git for module: MMM-pages
[2020-10-13 18:07:16.321] [INFO]   Checking git for module: MMM-GoogleAssistant
[2020-10-13 18:07:16.398] [INFO]   Checking git for module: MMM-Assistant2Display
[2020-10-13 18:07:16.446] [INFO]   Checking git for module: MMM-MicrosoftToDo
[2020-10-13 18:07:16.492] [INFO]   Checking git for module: MMM-AfterShip
[2020-10-13 18:07:16.539] [INFO]   Checking git for module: MMM-OpenmapWeather
[2020-10-13 18:07:16.587] [INFO]   Checking git for module: MMM-Fuel
[2020-10-13 18:07:16.634] [INFO]   Checking git for module: MMM-EmbedYoutube
[2020-10-13 18:07:16.681] [INFO]   Checking git for module: MMM-COVID19
[2020-10-13 18:07:18.885] [INFO]   Newsfeed-Fetcher: Broadcasting 40 items.
[2020-10-13 18:07:19.243] [INFO]   Newsfeed-Fetcher: Broadcasting 43 items.
[2020-10-13 18:07:21.643] [INFO]   Calendar-Fetcher: Broadcasting 0 events.
`

#############################################################################################
I also try to reinstall it by doing "npm install" in "/MagicMirror/modules/Assistant2Display", but it doesnt help. Furthermore the instalationoutput found 5 high vulnerabilities.

Here is the output of "npm audit":
#############################################################################################
`pi@raspberrypi:~/MagicMirror/modules/MMM-Assistant2Display $ npm audit

                       === npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Insecure Entropy Source - Math.random()                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ node-uuid                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.4.4                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ node-uuid                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/93                              │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ negotiator                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.6.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > accepts > negotiator                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/106                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fresh                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.5.2                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > fresh                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/526                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fresh                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.5.2                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > send > fresh                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/526                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ fresh                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.5.2                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > serve-static > send > fresh                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/526                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > debug                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > finalhandler > debug                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > send > debug                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > serve-static > send > debug                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mime                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 1.4.1 < 2.0.0 || >= 2.0.3                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > send > mime                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/535                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mime                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 1.4.1 < 2.0.0 || >= 2.0.3                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > serve-static > send > mime                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/535                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution Protection Bypass                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ qs                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=6.0.4 <6.1.0 || >=6.1.2 <6.2.0 || >=6.2.3 <6.3.0 ||        │
│               │ >=6.3.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @bugsounet/secure-a2d                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @bugsounet/secure-a2d > @bugsounet/cast > peer-dial >        │
│               │ express > qs                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1469                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 12 vulnerabilities (5 low, 2 moderate, 5 high) in 522 scanned packages
  12 vulnerabilities require manual review. See the full report for details.
`
#############################################################################################
Maybe someone can say me what's wrong.

Thanks in Advance

**Comment by bugsounet** [comment]
hi,

Thanks to verify your [MMM-GoogleAssistant structure](https://github.com/bugsounet/MMM-GoogleAssistant/wiki/Configuration-Sample#full--detailed-see-the-configuration-structure)

**Comment by JTprogramm** [comment]
Thanks for the quick answer, now it works:-)
