### ISSUE TITLE
Links are no longer showing

### ISSUE THREAD

**Issue by gelaw2** [bugsounet/MMM-Assistant2Display#136]
For me, Links and YouTube stopped working at the same time.  YouTube is now fixed and working, but Links remains broken.
For example, now the Google Assistant reads me the weather forecast, but there is no display of the link.

**Comment by bugsounet** [comment]
actually, i can't fix it because google server return no callback with links

**Comment by gelaw2** [comment]
Oh my.  I wonder how the Google Display devices work now?

**Comment by bugsounet** [comment]
this is no many doc about new api response... so i'm waiting...

**Comment by gelaw2** [comment]
Thanks for the feedback.  Hopefully Google will update favorably.

**Comment by bugsounet** [comment]
i hope too... because actually it's not the case!

**Comment by gelaw2** [comment]
To my surprise, it appears that YouTube is now broken again.  Did the google server change again?
