### ISSUE TITLE
Spotify not work

### ISSUE THREAD

**Issue by gfucka** [bugsounet/MMM-Assistant2Display#137]
Hi,
I follow all the instructions but if I says: "_Jarvis Alan Walker on Spotify_" it answer with : "_This is what I find on the web...._"
Youtube video, youtube cast etc.. works
But spotify not.

I hasn't a spotify premium account so I can't use librespot but I want MM play spotify on my Spotify PC App, so I put in connectTo the name of my pc (the one I see in spotify app).

Please help me to understand if I do something wrong or if is a module problem.

Thank you

**Comment by bugsounet** [comment]
and what wiki says ?

[Needed](https://github.com/bugsounet/MMM-Assistant2Display/wiki/spotify#needed)
