### ISSUE TITLE
I have a problem. You can search youtube. But, it doesn`t come out. -- This is a translator.

### ISSUE THREAD

**Issue by jinnij21** [bugsounet/MMM-Assistant2Display#138]
I have checked all configurations. But I couldn`t find what the problem was.

[Contents]
All installation and setting have been made.
Start running. SmartMirror... YouTube Michael Jackson Thriller.
Search is possible. But YouTube doesn`t come out.
Please help me.

Attempted to configure "OPENGL" but failed.

**Comment by bugsounet** [comment]
hi, GA found a YT title ?
see in the log.
You should have a response like this:
```
[ASSISTANT] Found YouTube Title: Michael Jackson - Thriller (Official Video) - videoId: XXXXXXX
```

**Comment by bbjoern** [comment]
Same issue here.. Got the response in the log like you wrote @bugsounet .. seems like random videos are played but most won't start playing

**Comment by bugsounet** [comment]
see if `electronOptions` and `address` fields are correct

**Comment by bbjoern** [comment]
address: "localhost",  <-- fixed the problem .. thanks @bugsounet
