### ISSUE TITLE
broken dependency to module "http-timer"

### ISSUE THREAD

**Issue by mthalhof** [bugsounet/MMM-Assistant2Display#139]
I just installed the latest version of MMM-GoogleAssistant and MMM-Assistant2Display (two wounderfull tools)
When i enable the MMM-Assistant2Display module (with the minimal config) in config.js i get this error at mm startup:

> [2020-11-02 13:11:39.450] [LOG]    Module helper loaded: MMM-GoogleAssistant
> [2020-11-02 13:11:39.464] [ERROR]  App threw an error during load
> [2020-11-02 13:11:39.465] [ERROR]  Error: Cannot find module '/opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/@szmarczak/http-timer/source'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:232:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
>     at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
>     at Function.Module._resolveFilename (/opt/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
>     at Function.Module._resolveFilename (/opt/MagicMirror/node_modules/module-alias/index.js:49:29)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:27)
>     at Module.require (internal/modules/cjs/loader.js:685:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (/opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/got/source/request-as-event-emitter.js:11:15)
>     at Module._compile (internal/modules/cjs/loader.js:786:30)
> [2020-11-02 13:11:39.468] [ERROR]  Whoops! There was an uncaught exception...
> [2020-11-02 13:11:39.469] [ERROR]  Error: Cannot find module '/opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/@szmarczak/http-timer/source'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:232:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
>     at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
>     at Function.Module._resolveFilename (/opt/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
>     at Function.Module._resolveFilename (/opt/MagicMirror/node_modules/module-alias/index.js:49:29)
>     at Function.Module._load (internal/modules/cjs/loader.js:531:27)
>     at Module.require (internal/modules/cjs/loader.js:685:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (/opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/got/source/request-as-event-emitter.js:11:15)
>     at Module._compile (internal/modules/cjs/loader.js:786:30) {
>   code: 'MODULE_NOT_FOUND',
>   path: '/opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/@szmarczak/http-timer/package.json',
>   requestPath: '@szmarczak/http-timer'
> }
> [2020-11-02 13:11:39.480] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> [2020-11-02 13:11:39.481] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
> [2020-11-02 13:11:39.623] [LOG]    Launching application.

but: the module is there...

> pi@mirror:~ $ ls -al /opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/@szmarczak/http-timer/package.json
> -rwxr-xr-x 1 pi pi 1910 Nov  1 15:26 /opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/@szmarczak/http-timer/package.json

Any idea how to fix it?

**Comment by bugsounet** [comment]
> [2020-11-02 13:11:39.465] [ERROR] Error: Cannot find module '/opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/@szmarczak/http-timer/source'

why do you install MagicMirror in `/opt` directory ?

please follow MagicMirror guide

**Comment by mthalhof** [comment]
> > [2020-11-02 13:11:39.465] [ERROR] Error: Cannot find module '/opt/MagicMirror/modules/MMM-Assistant2Display/node_modules/@szmarczak/http-timer/source'
> 
> why do you install MagicMirror in `/opt` directory ?
> 
> please follow MagicMirror guide

I might be blind... but in the official MM installation guide no specific installation directory is defined.

https://docs.magicmirror.builders/getting-started/installation.html#manual-installation
