### ISSUE TITLE
Spotify installation

### ISSUE THREAD

**Issue by renzo79** [bugsounet/MMM-Assistant2Display#140]
Hello,
I am trying to use the spotify integration. 
But when I am trying to use the Post-Installation steps and I am typing in "npm run spotify", I am getting following error Message:
pi@raspberrypi:~/MagicMirror/modules/MMM-Assistant2Display $ npm run spotify

> MMM-Assistant2Display@2.3.17 spotify /home/pi/MagicMirror/modules/MMM-Assistant2Display
> node installer/spotify-setup.js

/home/pi/MagicMirror/config/config.js:179
    cast: {
    ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant2Display/installer/spotify-setup.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MMM-Assistant2Display@2.3.17 spotify: `node installer/spotify-setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the MMM-Assistant2Display@2.3.17 spotify script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-11-04T18_29_16_613Z-debug.log

In the according Error file are following entries:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'spotify' ]
2 info using npm@6.14.6
3 info using node@v10.20.1
4 verbose run-script [ 'prespotify', 'spotify', 'postspotify' ]
5 info lifecycle MMM-Assistant2Display@2.3.17~prespotify: MMM-Assistant2Display@2.3.17
6 info lifecycle MMM-Assistant2Display@2.3.17~spotify: MMM-Assistant2Display@2.3.17
7 verbose lifecycle MMM-Assistant2Display@2.3.17~spotify: unsafe-perm in lifecycle true
8 verbose lifecycle MMM-Assistant2Display@2.3.17~spotify: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/modules/MMM-Assistant2Display/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sb$
9 verbose lifecycle MMM-Assistant2Display@2.3.17~spotify: CWD: /home/pi/MagicMirror/modules/MMM-Assistant2Display
10 silly lifecycle MMM-Assistant2Display@2.3.17~spotify: Args: [ '-c', 'node installer/spotify-setup.js' ]
11 silly lifecycle MMM-Assistant2Display@2.3.17~spotify: Returned: code: 1  signal: null
12 info lifecycle MMM-Assistant2Display@2.3.17~spotify: Failed to exec spotify script
13 verbose stack Error: MMM-Assistant2Display@2.3.17 spotify: `node installer/spotify-setup.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid MMM-Assistant2Display@2.3.17
15 verbose cwd /home/pi/MagicMirror/modules/MMM-Assistant2Display
16 verbose Linux 5.4.35-v7l+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "spotify"
18 verbose node v10.20.1
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error MMM-Assistant2Display@2.3.17 spotify: `node installer/spotify-setup.js`
22 error Exit status 1
23 error Failed at the MMM-Assistant2Display@2.3.17 spotify script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thanks for your help

**Comment by bugsounet** [comment]
Hi, too pretty this log! 

> /home/pi/MagicMirror/config/config.js:179
cast: {
^^^^

You have an example of structure [there](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration-Sample#full--detailed-see-the-configuration-structure)
So... you error is just before the line 179 of you config.js file
then see your line 178 and add the missing comma...

**Comment by renzo79** [comment]
Thousand thanks!!!
I´ve corrected the missing commas also in the documentation.

Best
