### ISSUE TITLE
Recipe "with-A2DSpotify.js" not installed

### ISSUE THREAD

**Issue by renzo79** [bugsounet/MMM-Assistant2Display#142]
Hello,

in the documentation was noted
"use with-A2DSpotify.js recipe for MMM-GoogleAssistant (autoinstalled in recipes directory)"

but it is missing after a succesfull installation. In the code I can not find and download it but where can I find it?

Thanks in Advance

**Comment by bugsounet** [comment]
it's installed automaticaly with npm install in `~/MagicMirror/modules/MMM-GoogleAssistant/recipes/`
