### ISSUE TITLE
stopCommand stops youtube videos but gives wrong answer

### ISSUE THREAD

**Issue by andia89** [bugsounet/MMM-Assistant2Display#143]
Hello, 

thanks for the great modules! Everything is working fine, so when I ask the assistant to play a video it nicely starts to play the video. However when I want to stop the video I say "stop Youtube" (that is the phrase I have set in my config file) and the video stops, however the assistant answers with "Sorry I don't understand" (even though it stopped the video)

In my config file I have 

```
{
			module: "MMM-GoogleAssistant",
			position: "fullscreen_above",
			config: {
				debug: true,
				A2DServer: {
					useA2D: true,
					stopCommand: "stop YouTube",
					useYouTube: true,
					displayResponse: true,
				},
				assistantConfig: {
					lang: "en-US",
					latitude: 48.215408,
					longitude: 16.37459,
				},
				responseConfig: {
					screenRotate: true, 
					useAudioOutput: true, 
					useNative: true, 
					playProgram: "mpg321",
				},
				micConfig: { // put there configuration generated by auto-installer
					recorder: "arecord",
					device: "plughw:2",
				},
			}
		},

{
			module: "MMM-Assistant2Display",
			position: "top_left",
			config: {
				useYoutube: true,
				debug:true,
				photos: {
					usePhotos:true,
				},
				cast: {
					useCast: true, 
					castName: "MagicMirror",
					port: 8569
				},
				NPMCheck: {
					useChecker: true,
					useAlert: false,
				}
			}
		},
```

**Comment by bugsounet** [comment]
Hi, sure the stop command play the google response. i can't control it

in your case, if you have define "stop youtube", google server will respond the natural answer and GA will play it
I don't make script a code for don't play reponse for defined stop command

So, just change your stop command in GA

**Comment by andia89** [comment]
Thanks I get it. That's why you suggest the thank you command in the wiki
