### ISSUE TITLE
I have a question about YouTube function

### ISSUE THREAD

**Issue by leejaehoon24** [bugsounet/MMM-Assistant2Display#146]
I read Wiki and installed it. But [ASSISTANT] Found YouTube Title: Logs don't appear when you mention Smart Mirror YouTube <Your Request>.
[ASSISTANT] YouTube search function initialized
Is the log installed normally when there a normal installation?
How should I operate it if it's installed?

**Comment by bugsounet** [comment]
hi,
if you see `[ASSISTANT] YouTube search function initialized`
it's means the json file is created (i don't check inside if correct)

for testing, just follow wiki

**Comment by bojuelkjeldsen** [comment]
Hi - great job with both GoogleAssistant (GA) and Assistant2Display! 

Both runs in MMM together with MMM-face-reco-DNN very good!

I have GA installed with MMM-Assistant2Display. With GA I can ask to see Michael Jackson in Youtube. This works fine. However, the "stop", does not work? I activate GA and say "stop" when youtube is running - but GA does not know the "stop". Should there be a recipe installed? ("with-MMM-youtube.js") Or something with TelegramBot - that I have not installed? 

Best regards!
