### ISSUE TITLE
How can I activate the youtube module in other language

### ISSUE THREAD

**Issue by chmylife** [bugsounet/MMM-Assistant2Display#150]
Thank you very much for providing such a wonderful program.
I have a problem about using youtube module.
I think it only works in English when I try to operate the module. Is it right? 
If I'm wrong, please let me know how to change the keyword 'youtube' in another language?
I want to run YouTube in Korean.

**Comment by bugsounet** [comment]
Not yet implented I will try to do it soon

**Comment by bugsounet** [comment]
i just update it,  you can now change `youtube` keyword by the Korean word

See GA config and the new A2DServer configuration (youtubeCommand)
