### ISSUE TITLE
Link is empty array

### ISSUE THREAD

**Issue by phungorquan** [bugsounet/MMM-Assistant2Display#153]
Hi @bugsounet,

For a long time i had not used G.A, today i checked it again and didn't know why it didn't show Web iFrame as normally.
It still receive my voice and response but it did not show anything.
I didn't know why :(

When i tried to debug some information. It shown me informatino below

```
[ASSISTANT] ASSISTANT_RESULT {
  error: null,
  action: { requestId: '5fdd2cf5-0000-22a5-ab6e-3c286d3761d6' },
  text: null,
  screen: {
    text: "Here's a result from Wikipedia",
    links: [],
    photos: [],
    path: '/home/xiu/MagicMirror/THESIS/modules/MMM-GoogleAssistant/tmp/lastScreenOutput.html',
    uri: 'tmp/lastScreenOutput.html'
  },
  audio: {
    path: '/home/xiu/MagicMirror/THESIS/modules/MMM-GoogleAssistant/tmp/lastResponse.mp3',
    uri: 'tmp/lastResponse.mp3'
  },
  transcription: { transcription: 'Wikipedia', done: true },
  continue: false,
  volume: null,
  lastQuery: {
    type: 'MIC',
    key: null,
    lang: 'en-US',
    useScreenOutput: true,
    useAudioOutput: true,
    status: 'standby',
    chime: true
  }
}

```

Because everything still OK before, :(.

Best regards,
Thanks!

**Comment by bugsounet** [comment]
hi, just because google server send an array links empty

it's an SDK and not an release google assistant project sorry

Actually Google Server return no many links since they have updated SDK google assistant server
it's very limited actually...

**Comment by phungorquan** [comment]
Hmmm, 
Did you fix this problem?
Because i think this is a main function of our G.A and A2D :(

**Comment by bugsounet** [comment]
euh ... I don't work with Google enterprise, sorry

IF Google don't send ANY link ... I can't display it

**Comment by phungorquan** [comment]
If like that.
How can you show if you want to?.
Are there any solution or any search keyword or something?

At the moment, Do your system show or not show?

**Comment by bugsounet** [comment]
I'm not magician... If Google send no link... I can't display no link...
