### ISSUE TITLE
No audio in youtube.

### ISSUE THREAD

**Issue by phucthai610** [bugsounet/MMM-Assistant2Display#155]
First,thanks you so much.But right now I do have one big issue: I don't get audio when playing youtube videos.
Google Assistant is answering my questions with perfect audio outputs, but when any youtube video starts they are all muted. Playing youtube videos in chromium works fine,listening music on sportify very good.Can you help me?

**Comment by bugsounet** [comment]
maybe [this](https://github.com/bugsounet/MMM-GoogleAssistant/wiki#tip) can help ?

**Comment by phucthai610** [comment]
Hi, what's your opinion? I don't understand.
