### ISSUE TITLE
Question - Cast and Youtube Window dimension and position

### ISSUE THREAD

**Issue by robertalexa** [bugsounet/MMM-Assistant2Display#159]
Hi Cedric,

Just wondering if you plan on implementing options for casting and play youtube video in a window for which you can set the dimension.

For reference, see the [Screencast](https://github.com/kevinatown/MMM-Screencast) module which gives you the option to pass details in the config
`{
            module: "MMM-Screencast",
            disabled: false,
            position: "bottom_right", // This position is for a hidden <div /> and not the screencast window
            config: {
                position: "center",
                height: 600,
                width: 1000,
                castName: "Magic Mirror"
            }
        },`

I really like the echosystem you have created around Google Assistance and I feel that this could be an useful feature, allowing people to play a video in a certain position of the mirror while having the rest of the modules still visible, and more importantly, a predominantly dark, screen. To give an example, my Smart Mirror is designed as a vanity mirror for my girlfriend, and using Screencast, we can play a video relatively small in the center of the screen, while the rest of the mirror will still be dark enough to allow usage for putting on makeup :)

Best regards and wish you good fortune in the new year,
Rob

**Comment by bugsounet** [comment]
sorry about this but i will not code your request.
A2D policy is popup for displaying only in fullscreen (it's my wanted feature since start)

if you want this feature, just fork and code it ;)
or just disable A2D cast module, youtube and use orthers
