### ISSUE TITLE
Issues with Stop and Youtube

### ISSUE THREAD

**Issue by jaxonstagecrew** [bugsounet/MMM-Assistant2Display#16]
I am also currently having issues with the stop command.  Doesn't seem to work on any link.  Also when im in youtube, it disables my microphone so im not able to back out.  Everything else has been working flawlessly

**Comment by jaxonstagecrew** [comment]
Found the issue with Youtube, my microphone is picking up too much noise so I have to turn the volume off for it to hear me.  Still having issues with stop command though

**Comment by bugsounet** [comment]
hi,

AMk2 search only the exact match of `stop` or `stoppe`
maybe in your language it's not exactly this word
if you use fullscreen ui, you will see the exact word when you says `stop`
give me it ;)
i have not set again a database for it

**Comment by bugsounet** [comment]
I think i will set an feature for key word `stop` in next release

**Comment by bugsounet** [comment]
Personnal command to `stop` A2D will be integred to the next release

> Found the issue with Youtube, my microphone is picking up too much noise so I have to turn the volume off for it to hear me. Still having issues with stop command though

i can so something for this.
maybe by increasing the sensitivity of the microphone and the recognition of your detector

**Comment by jaxonstagecrew** [comment]
Just updated and its working great.  Thanks!
