### ISSUE TITLE
[ERROR] Youtube search not set!

### ISSUE THREAD

**Issue by ChrissyT4** [bugsounet/MMM-Assistant2Display#161]
I have enabled YouTube in the config and downloaded the API yet am greeted with: [ERROR] YouTube search not set!  every time. Any fix? It's probably very easy and I am overlooking it.

**Comment by bugsounet** [comment]
hi, do you read the wiki part in A2D for youtube use ?

**Comment by ChrissyT4** [comment]
I remember looking there and seeing nothing. Sorry for the trouble.
