### ISSUE TITLE
Title bottom of Youtube

### ISSUE THREAD

**Issue by namcktv** [bugsounet/MMM-Assistant2Display#162]
Can I remove title bottom of Youtube? 

-
![IMG_20210108_232111](https://user-images.githubusercontent.com/10647323/104038903-440f4700-5208-11eb-9a5f-6f1db724fe69.jpg)

**Comment by bugsounet** [comment]
Use fullscreen_above position

**Comment by namcktv** [comment]
The module use fullscreen_above position?

**Comment by bugsounet** [comment]
Only GA

A2D will look the config of GA and configure properly
