### ISSUE TITLE
I installed by mistake can it be uninstall

### ISSUE THREAD

**Issue by DJRamm** [bugsounet/MMM-Assistant2Display#166]
I have a brain injury and mistakenly install mmm-Ass2d now i need to remove it is it possible. Please don't say read wiki 

Thanking You DJ Ramm

**Comment by bugsounet** [comment]
Desinstall MMM-Assistant2Display:
```sh
cd ~/MagicMirror/modules
rm -rf MMM-Assistant2Display
```

If you want to desinstall MMM-GoogleAssistant:

```sh
cd ~/MagicMirror/modules
rm -rf MMM-GoogleAssistant
```

**optional:**
if you want to desintall MagicMirror:
```sh
cd ~/
rm -rf MagicMirror
```

**Comment by DJRamm** [comment]
Thank you very much for that.

DJ Ramm
