### ISSUE TITLE
Links don't show up

### ISSUE THREAD

**Issue by David-LETINAUD** [bugsounet/MMM-Assistant2Display#24]
Hi,
Since a recent update, Assistan2Display no longer displays links to me while the display of photos and youtube videos still works. The screen stays black for 1 minute but the page does not display.
I tried with the basic configs but it doesn't work either, thanks in advance for your help.

/********CONFIG : MMM-AssistantMk2 **********/
{
		  module: "MMM-AssistantMk2",
		  position: "bottom_bar",
		  config: {
		    useA2D: true,
		    debug:true,
		    ui: "Simple",
		    record: {
		      recordProgram : "arecord",  
		      device        : "plughw:1",
		    },
		    notifications: {
		      ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
		      ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
		    },
		    recipes: ["with-MMM-Hotword.js"],
		    "default": {
				profileFile: "default.json",
					lang: "fr-FR"
						 }
		  }
		},

/********CONFIG : MMM-Assistant2Display**********/
{
  module: "MMM-Assistant2Display",
  position: "top_left",
  config: {
    debug:false,
  }
},

/******* In debug mode *******/
[2020-05-04 14:09:46.762] [LOG]    [AMK2] ASSISTANT_RESULT {
  session: 1588594182466,
  error: null,
  action: { requestId: '5eb38fa3-0000-2fb9-9c22-3c286d346ae2' },
  text: null,
  screen: {
    text: '"Yoda — Wikipédia" ((fr.m.wikipedia.org – ' +
      'https://fr.m.wikipedia.org/wiki/Yoda))\\nYoda est un personnage ' +
      "fictif de l'univers Star Wars. Il apparaît pour la première " +
      'fois dans Star Wars, ...',
    links: [ 'https://fr.m.wikipedia.org/wiki/Yoda' ],
    photos: [],
    help: [ 'Que sais-tu faire ?' ],
    trysay: 'Try saying…',
    path: '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/lastScreenOutput.html',
    uri: 'tmp/lastScreenOutput.html'
  },
  audio: {
    path: '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/lastResponse.mp3',
    uri: 'tmp/lastResponse.mp3'
  },
  transcription: { transcription: 'Yoda sur Wikipédia', done: true },
  continue: false,
  volume: null,
  lastQuery: {
    type: 'MIC',
    profile: { profileFile: 'default.json', lang: 'en-US' },
    key: null,
    lang: null,
    useScreenOutput: true,
    useAudioOutput: true,
    useHTML5: true,
    session: 1588594182466,
    status: 'standby',
    chime: true,
    secretMode: false,
    sayMode: false
  }
}

**Comment by bugsounet** [comment]
Bonjour,
Avez-vous activé la fonction [webview](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration#configuration) comme indiqué dans le [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki) ?

**Comment by David-LETINAUD** [comment]
Ah oui en effet, ça fonctionne mieux comme ça.. 
Je me suis focalisé sur la page wiki "Configuration-Structure" parce que j'avais vu pas mal de changement..
Merci pour votre aide

**Comment by bugsounet** [comment]
pas de souci !

notes: 
D'autres changements sont encore à venir ... (surprise...)
Je vais finir par concurrencer le Google Nest ;)

**Comment by David-LETINAUD** [comment]
Hâte de voir ça =)
A ce rythme, Google a du souci a se faire ^^
