### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by marcgrc** [bugsounet/MMM-Assistant2Display#27]

**Comment by marcgrc** [comment]
Don’t play 
Why ?

**Comment by marcgrc** [comment]
First update yes 
After last update don t play

**Comment by bugsounet** [comment]
sorry, i don't understand ...
can you explain your problem ?

**Comment by marcgrc** [comment]
when I say it raises the volume to 50% he says ok I raise the volume to 50% but in fact it does not raise it

**Comment by bugsounet** [comment]
works before update ?

**Comment by marcgrc** [comment]
Hes

**Comment by bugsounet** [comment]
what is the command do you use for updating ?

**Comment by marcgrc** [comment]
git pull
npm run update

**Comment by bugsounet** [comment]
try to launch MM manually
(stop `pm2` process if used)

```sh
cd ~/MagicMirror
npm start
```
and give log

**Comment by marcgrc** [comment]
how do I 
 give log ?

**Comment by bugsounet** [comment]
just copy/past the result of the command

**Comment by marcgrc** [comment]
![58FFD469-83D7-442E-9F82-30CC37CF244E](https://user-images.githubusercontent.com/19284774/81478701-4192c280-921f-11ea-9e13-1b9d24a17a84.jpeg)

**Comment by marcgrc** [comment]
![1C9796C0-FF4C-48BA-B518-3921ECADCFA5](https://user-images.githubusercontent.com/19284774/81478719-566f5600-921f-11ea-845e-0406a85c0f81.jpeg)

**Comment by bugsounet** [comment]
not other ?

**Comment by marcgrc** [comment]
![image](https://user-images.githubusercontent.com/19284774/81478800-deedf680-921f-11ea-8050-2a6c94ae0348.jpg)

**Comment by marcgrc** [comment]
![image](https://user-images.githubusercontent.com/19284774/81478837-12c91c00-9220-11ea-9587-4ae313bacfbb.jpg)

**Comment by bugsounet** [comment]
humm ... ok

i test with my platform, and it don't works
i suppose google change API.
I will inspect

**Comment by marcgrc** [comment]
Ok great we attend you 💪💪

**Comment by marcgrc** [comment]
Hello nothing ?

**Comment by bugsounet** [comment]
API Google return no volume control actually ...
I can't fix it actually, so just wait

**Comment by bugsounet** [comment]
I have do some new code for it in AMk2
let's update it to v3.3.1 and it should works

**Comment by marcgrc** [comment]
Yes I have seen
Great
