### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by emberhood** [bugsounet/MMM-Assistant2Display#30]
Hi am trying to install the module and i get this error message.

pi@raspberrypi:~/MagicMirror/modules/MMM-Assistant2Display $ npm install

MMM-Assistant2Display@1.5.1 preinstall /home/pi/MagicMirror/modules/MMM-Assistant2Display
installer/preinstall.sh

Welcome to Assistant2Display "1.5.1",

Checking OS...
OS Detected: linux-gnueabihf (raspbian 10 armv7l)

Installing all library...

npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
npm ERR! Unexpected end of JSON input while parsing near '...","jade":"~0.30.0","h'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-12T10_05_46_545Z-debug.log

**Comment by bugsounet** [comment]
wait, i will test

**Comment by bugsounet** [comment]
weird ...
it's works ...

```sh
npm install

> MMM-Assistant2Display@1.5.1 preinstall /home/bugs/MagicMirror/modules/MMM-Assistant2Display
> installer/preinstall.sh

Welcome to Assistant2Display "1.5.1",

Checking OS...
OS Detected: linux-gnu (debian 10 x86_64)

Installing all library...

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-uuid@1.4.1: Use uuid module instead

> epoll@4.0.0 install /home/bugs/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll
> node-gyp rebuild

make : on entre dans le répertoire « /home/bugs/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build »
  CXX(target) Release/obj.target/epoll/src/epoll.o
  SOLINK_MODULE(target) Release/obj.target/epoll.node
  COPY Release/epoll.node
make : on quitte le répertoire « /home/bugs/MagicMirror/modules/MMM-Assistant2Display/node_modules/epoll/build »

> @bugsounet/pir@1.0.4 postinstall /home/bugs/MagicMirror/modules/MMM-Assistant2Display/node_modules/@bugsounet/pir
> electron-rebuild

✔ Rebuild Complete
```

for you it's seams an `npm` package broken ...
actually i can't reproduce it

maybe by updating npm program

try:

```sh
sudo npm install -g npm
```

**Comment by emberhood** [comment]
pi@raspberrypi:~/MagicMirror/modules/MMM-Assistant2Display $ sudo npm install -g npm
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/npm failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-12T12_15_57_045Z-debug.log

**Comment by bugsounet** [comment]
> npm ERR! code EAI_AGAIN

means : no internet connexion or no DNS server available
so configure it ... or autorize it in firewall / DNS request
