### ISSUE TITLE
demande particulière concernant le module screen

### ISSUE THREAD

**Issue by bigjojo** [bugsounet/MMM-Assistant2Display#31]
bonjour,
je suis parti sur ton recipe radio pour utilise via un recipe vlc pour regardé la télé depuis un flux de ma dreambox, ca fonctionne nickel en reconnaissance vocale.
par contre j'ai un petit souci car après x temps indiqué pour screen l'écran s'éteint (normal).
je me demandais si tu avais peut etre une commande a me conseiller pour placer une commande dans le module screen ou dans le recipe vlc afin que celui ci n'éteint pas l'écran pendant que vlc ou kodi (j'avais deja fait fonctionné kodi en parallèle avec reconnaissance vocale rechercher et lancer un film-serie de mon server avec l'ancienne version mk2)  est en fonctionnement.

merci pour ton aide.

**Comment by bugsounet** [comment]
oui, c'est tout a fait possible de `lock` / `unlock` le screen (c'est a dire laisser l'ecran alumé ou redémarrer le compteur)
mais ... j'ai pas coder cette possibilité en externe (en dehors de A2D via notification).
ça me fait penser qu'avec un de mes nouveaux modules (FreeboxTV), j'en ai besoin et pas pensé à ça !
Donc bonne nouvelle, je vais le mettre en place très prochainement !

**Comment by bugsounet** [comment]
aussitôt demandé ... aussitôt codé :)

14/05/2020 (v1.5.2)
**ADD**: notification received `A2D_LOCK` and `A2D_UNLOCK`

**Comment by bigjojo** [comment]
bonsoir, nickel merci, me reste a faire la mise a jour. lol
