### ISSUE TITLE
Magic mirror qui s'arrête

### ISSUE THREAD

**Issue by jeff44850** [bugsounet/MMM-Assistant2Display#33]
Bonjour
Après de multiples réinstallation de hotword assistant2display amk2 Magic mirror s'arrête avec apparement un soucis avec Spotify !!
Est ce que tout est lié ?
Tout fonctionnais bien il y a deux jours et plus rien ne va ? 
Merci de votre réponse
Cordialement

**Comment by bugsounet** [comment]
bonsoir,
quel est le rapport avec une issue d'A2D ?

Merci d'ouvrir une issue dans le bon module ;)

Merci par avance
@bugsounet
