### ISSUE TITLE
Magic mirror redémarre sans cesse !

### ISSUE THREAD

**Issue by jeff44850** [bugsounet/MMM-Assistant2Display#34]
Bonjour
Après de multiples réinstallation de hotword assistant2display amk2 Magic mirror s'arrête avec appartement un soucis avec Spotify !!
Est ce que tout est lié ?
Tout fonctionnais bien il y a deux jours et plus rien ne va ? 
Merci de votre réponse
Cordialement

**Comment by bugsounet** [comment]
donc ...
je repete si c'est Spotify...

>bonsoir,
quel est le rapport avec une issue d'A2D ?
Merci d'ouvrir une issue dans le bon module ;)
Merci par avance
@bugsounet

car **AUCUN** de ses modules ne gere Spotify

**Comment by jeff44850** [comment]
Bonjour
Je pensais qu'ils étaient en rapport puisque plus rien n'a fonctionner lors
des mises a jour où des réinstallation !
Soit le miroir est noir soit il redémarre soit la détection d'alexa ( dans
mon cas ) ne fonctionne plus 😒
