### ISSUE TITLE
unable to cast youtube video

### ISSUE THREAD

**Issue by patacco** [bugsounet/MMM-Assistant2Display#35]
hi everyone  and thanks for all...
i'm not able to cast video from youtube to magicmirror.....it not appear in list to cast to....

my configuration : 
// ------------------------MMM-Assistant2Display configuration -------------------
		{
		module: "MMM-Assistant2Display",
		position: "top_left",
			config: {
			debug:false,
			useYoutube: true,
			},
			cast: {
  			useCast: true,
   			//castName: "MagicMirror_A2D",
    			//port: 8569
  			},

		},

thanks

**Comment by bugsounet** [comment]
hi, in the [sample structure](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration-Sample#full--detailed-see-the-configuration-structure),
you can see `cast` block inside config {} and not ouside it

**Comment by patacco** [comment]
thanks
