### ISSUE TITLE
Plus d'affichage 

### ISSUE THREAD

**Issue by jeff44850** [bugsounet/MMM-Assistant2Display#36]
Je n'est plus d'affichage ou de son a la détection avec hotword
J'ai effectué les mises a jour des 3 modules hotword MK2 et A2D et depuis plus rien 
J'ai certainement loupé une étape ou une config a modifier mais je suis un peu perdu avec toutes les versions 
Pourquoi obligé a faire des mises a jour alors que pour moi ça fonctionnais et me convenais 😒

**Comment by bugsounet** [comment]
1) tout dépend quel command a été utlisé lors d'une mise a jour
si vous avez fais un `git pull` c'est normal que ça coince
Il faut utiliser `npm run update` -> c'est ecrit dans le readme

2) personne ne vous oblige a faire les mise a jours et également utiliser ces modules.
je fais ces modules pour moi meme en premier et je le partage ...

Je ne demande Absolument rien !
Dois-je faire payer tout le monde pour utiliser ça ?
Quand je vois des Issues comme ça ... ça me donne envie de mettre tous les modules en privé et basta plus d'assistant
Je vais finir par garder mon savoir pour moi meme !
J'était en train d'écrire le code de Spotify, ben comme ça c'est fait ... c'est en mode `ne pas coder`

bonne journée

**Comment by jeff44850** [comment]
Ne le prenez pas comme ça
Ce n'est pas une critique
Je suis juste étonné que lorsqu'il y a une mise a jour de disponible les
modules ne fonctionne plus
Concernant la mise à jour je suis bien passé par rien npm update
