### ISSUE TITLE
petit renseignment sur les commandes radio

### ISSUE THREAD

**Issue by stik57** [bugsounet/MMM-Assistant2Display#37]
salut ton module est super et merci pour ton suivi avec tes mise a jours.
J aurais ce pendant une question surement bète .
une fois la radio lancée tout fonctionne mais quelle est  la commande pour la couper.
et est ce que c est normal que lassistant a un temps de reponse plus long. merci

**Comment by bugsounet** [comment]
Bonjour,

La commande stop est géré par AMk2 avec la feature [A2DStopCommand](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Configuration-Structure#field-a2dstopcommand)
vous trouverez ou la placer dans la [structure](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Configuration-Sample#full--detailed-see-the-configuration-structure)

En ce qui concerne le temps de réponse, tout dépend de la configuration utilisée et surtout du détecteur.
