### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by renzo79** [bugsounet/MMM-Assistant2Display#44]
Hello,

at the moment I am working for some prepared Recipes.

Radio-DE --> I think I will finish this this week

Replacement NEWPIR--> here I need a bit assistance:
The Module NEWPIR had commands to switch on and Off the display with:

    "NEWPIR_TURNOFF": {
      notificationExec: {
        notification: "USER_PRESENCE",
        payload : false|true
      },

Is there something similiar with the integrated PIR-Function of the A2D?

Thanks

**Comment by bugsounet** [comment]
Closed, Personal A2D v2 version

**Comment by renzo79** [comment]
Hey,

I am really sorry to hear about your decision to close this project. From my point of view, it is the best and most powerfull project for the MM.
If you need some assistance to reopen this project please let it me know!!
I´ve limited coding skills but I could configure some recipes or take over mgm. or documentation for you.

I wish you the best
