### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by Ryan792** [bugsounet/MMM-Assistant2Display#57]
Can you please take a look at my config file? youtube is not working.

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
  address: "localhost",
  electronOptions: {
    webPreferences: {
      webviewTag: true
    }
  },
  port: 8080,
  
	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "MMM-GoogleAssistant",
			position: "fullscreen_above",
			config: {
				debug: false,
				assistantConfig: {
					latitude: 51.508530,
					longitude: -0.076132,
					},
					micConfig: { // put there configuration generated by auto-installer
						recorder: "arecord",
						device: "plughw:2"
						},
						snowboy: {
							audioGain: 2.0,
							Frontend: true,
							Model: "smart_mirror",
							Sensitivity: null
							},
							snowboy: {
								audioGain: 2.0,
								Frontend: true,
								Model: "smart_mirror",
								Sensitivity: null
								},
								A2DServer: {
									useA2D: true,
									 },
						}
		},	
		{
			module: "MMM-YouTube",
			position: "top_right",
			},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by bugsounet** [comment]
MMM-Assistant2Display is not installed.
there is no config about it

**Comment by Ryan792** [comment]
Thank you so much!:) I forgot add to in config file. Youtube is working now.
I am using snowboy to use Smart_mirror instead of default "javris". Is the config wrong?

**Comment by Ryan792** [comment]
Ohk, Thank you much for pointing this out. I will fix this.
