### ISSUE TITLE
Cast & controlling other modules

### ISSUE THREAD

**Issue by hm1234** [bugsounet/MMM-Assistant2Display#60]
I have enabled cast using the default config but it does not show up in my YouTube app. 
![Screenshot_20200610-000042](https://user-images.githubusercontent.com/13208530/84225557-70fe4e80-aaad-11ea-9b9e-6bbb44e1a3f9.jpg)

I wanted to know if it was possible to control mmm-page to be able to switch pages with this?

**Comment by lxne** [comment]
> I have removed MMM-Volume

Hi hm1234, removing it did what?
Problems solved?

**Comment by hm1234** [comment]
It didn't just wanted to state that since it showed in the picture. I reinstalled raspberry os and Magic Mirror and modules and the cast shows up within the YouTube app but when I click it to cast it takes me to a black screen and nothing happens

**Comment by lxne** [comment]
Did you add the following to your config.js?
```
  electronOptions: {
    webPreferences: {
      webviewTag: true
    }
  },
```
[See wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration#magicmirror-configuration)

**Comment by bugsounet** [comment]
*sigh*

**Comment by bugsounet** [comment]
hi, We think your issue is now solved.
Reopen it if needed
