### ISSUE TITLE
No audio in youtube overlay.

### ISSUE THREAD

**Issue by lxne** [bugsounet/MMM-Assistant2Display#61]
First I wanna thank you for your awesome assistant modules. In fact calling them only 'modules' is a modest understatement. This is more like a full fledged assistant system.

But right now I do have one big issue: I don't get audio when playing youtube videos.
Google Assistant is answering my questions with perfect audio outputs, but when any youtube video starts they are all muted. Playing youtube videos in chromium works fine.
Do you have any idea?

--
_pi 3b+, buster, mm 2.11.0, MMM-GoogleAssistant 2.0.1
Respeaker 2-Mics Hat, Grove PIR sensor, Grove gesture sensor_

**Comment by bugsounet** [comment]
Frankly, for the moment, I don't know.
A2D loads the JS library with the default volume (100%).

I haven't had this kind of problem yet

**Comment by chanapai** [comment]
same problem

**Comment by lxne** [comment]
Disabling all other modules didn't help. I tried to play around with some audio settings. At some point I realized that pulseaudio was installed. When I uninstalled it I did get audio in youtube but the clip played extremely slow. I figured that I tinkered too much with my MagicMirror...
I did a new clean install on my setup and now it works.

**Comment by bugsounet** [comment]
try to enable Hardware accelerator `OpenGL` in `raspi-config`

**Comment by lxne** [comment]
> try to enable Hardware accelerator `OpenGL` in `raspi-config`

Good idea for pi 4 users. But very problematic on a pi 3.

**Comment by bugsounet** [comment]
why ? i do it too in rpi3 b+

**Comment by lxne** [comment]
> why ? i do it too in rpi3 b+

So you have activated 'fake kms' or 'full kms'?
If I activate full kms the assistant does not react to my questions anymore and with fake kms the assistant reacts but I get very strange display lags (seems very buggy).
Could you share you exact config.txt entries?
