### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by renzo79** [bugsounet/MMM-Assistant2Display#62]
Hello,

I´ve no idea why, but youtube isn´t starting here. When I cast a youtoube video, youtoube is starting without any errors on the mirror. 
It seems, that the mirror is also detecting a youtube link, because I am getting a special sound response. But than the mirror is not starting the video, he is getting back into the main window.

Thanks for your help

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
			     electronOptions: {
			  webPreferences: {
			webviewTag: true
		}
	    },
	port: 8080,
	ipWhitelist: [], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "de",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [
		{
			module: "alert",
		},
	
		{
			module: "clock",
			position: "top_left"
		},
		
{
  module: "MMM-GoogleAssistant",
  position: "fullscreen_above",
  config: {
    debug: false,
    assistantConfig: {
      lang: "de-DE",
        projectId: "magicmirror2020-e30a9", // Required to use gaction.
      modelId: "magicmirror2020-e30a9-danielsspiegel-8z1sjh", // (OPTIONAL for gaction)
      instanceId: "Daniels_Spiegel", // (OPTIONAL for gaction)
      latitude: 52.516751,
      longitude: 13.307844,
    },
    responseConfig: {
      useScreenOutput: true,
      screenOutputCSS: "screen_output.css",
      screenOutputTimer: 5000,
      activateDelay: 250,
      useAudioOutput: true,
      useChime: true,
      newChime: false
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1",
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    snowboy: {
      audioGain: 2.0,
      Frontend: true,
      Model: "jarvis",
      Sensitivity: null
    },
    A2DServer: {
      useA2D: true,
      stopCommand: "stop"
    },
    recipes: [ "with-MMM-Hotword.js", "with-MMM-TelegramBot.js", "Reboot-Restart-Shutdown.js", "with-MMM-NewPIR.js", "with-MMM-Youtube.js","with-radio_de.js" ]
  }
},	
	{
  module: "MMM-Assistant2Display",
  position: "top_left",
  config: {  
    debug:false,
    useYoutube: true,
    links: {
      useLinks: true,
      displayDelay: 60 * 1000,
      scrollStep: 25,
      scrollInterval: 1000,
      scrollStart: 5000,
      scrollActivate: false,
      verbose: false
    },
    photos: {
      usePhotos: true,
      displayDelay: 10 * 1000,
    },
    volume: {
      useVolume: true,
      volumePreset: "ALSA"
    },
    briefToday: {
      useBriefToday: false,
      welcome: "brief Today"
    },
    screen: {
      useScreen: true,
      delay: 5 * 60 * 1000,
      turnOffDisplay: true,
      ecoMode: true,
      displayCounter: true,
      text: "Auto Turn Off Screen:",
      detectorSleeping: false,
      governorSleeping: false,
      rpi4: true
    },
    pir: {
      usePir: true,
      pin: 26,
      reverseValue: false
    },
    governor: {
      useGovernor: false,
      sleeping: "powersave",
      working: "ondemand"
    },
    internet: {
      useInternet: false,
      displayPing: false,
      delay: 2* 60 * 1000,
      scan: "google.fr",
      command: "pm2 restart 0",
      showAlert: true
    },
    TelegramBot: {
      useTelecastSound: true,
      TelecastSound: "TelegramBot.ogg"
    },
    cast: {
      useCast: true,
      castName: "Daniels Spiegel",
      port: 8569
    },
  }
},

**Comment by lxne** [comment]
Did you try it with more basic settings?

```
{
  module: "MMM-Assistant2Display",
  position: "top_left",
  config: {
    debug:false,
  }
},
```
Does youtube work with this?

**Comment by renzo79** [comment]
Hi,

thanks for your support. I´ve tried this as well but saidly without success.
I am also getting no output in my debug console. It seems, that the link will found but any error in the 2Display module is. Is there any log which I don´t know?

Best

**Comment by lxne** [comment]
Sorry, I can't tell.
How hold is your MagicMirror installation?
I had a lot of issues with my old one. When I started from scratch everything went quite fine.

**Comment by bugsounet** [comment]
hi,
remove ANY `recipes` of GA config
remove `MMM-YouTube` module or disable it
remove `MMM-Hotword` module or disable it
remove `MMM-NewPIR` module or disable it

I think you search  issue ... you must have a lot of conflit.
I do some fresh install last day with 2 RPI (3B+ and 4) there no problem

**Comment by lxne** [comment]
@renzo79 Right now I do have the same issue.
Have you been able to solve your problem?

**Comment by lxne** [comment]
GoogleAssistant just reacts as if A2D wasn't installed.
It just doesn't show me Youtube videos as it used to do.
I tried two new installations from scratch. One RPI3B+ and one RPI4.
Both now running MM 2.12.0
Did Google change something?

**Comment by bugsounet** [comment]
hi, we think your issue is now solved.
Repoen it if needed
