### ISSUE TITLE
How to leave ?

### ISSUE THREAD

**Issue by 0rion12** [bugsounet/MMM-Assistant2Display#63]
hello, 
first of all, a huge thank you for all the work you have provided! the installation of the assistant is greatly simplified thanks to you.

I would just like to know what to say to the assistant so that he stops playing a youtube video or the radio for example.

**Comment by bugsounet** [comment]
personnalize `stopCommand` in your `A2DServer {}` GA config

**Comment by 0rion12** [comment]
Oh OK thank you!

**Comment by lxne** [comment]
I changed the stopCommand to 'Danke' (thank you). Because then most of the time you get a quite natural reaction from the assistant.
