### ISSUE TITLE
Comment arrêter la radio - How to stop radio on "with-radio_fr.js"

### ISSUE THREAD

**Issue by Tolosan31** [bugsounet/MMM-Assistant2Display#64]
Bonjour,

Bravo et félicitations pour cette application !

Une question : une fois la radio lancée, comment peut-on l'arrêter sans éteindre le Raspberry ?

Cordialement.

**Comment by bugsounet** [comment]
Bonjour,
pas besoin d'éteindre le raspberry, il suffit simplement de lire le [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki#notes)
