### ISSUE TITLE
When activating Assistant2Display, Smart Mirror with Google Assistant Freezes after my command.

### ISSUE THREAD

**Issue by kondef** [bugsounet/MMM-Assistant2Display#7]
I have installed MMM-assistant, hotword and assistant2display. When i activate the assistant2display and i wake up device with  "smart mirror" then the system freezes in the full screen of google assistant without listening to any firther command. It goes back only with exit force. Whenever i take out of the config file the assistant 2 display then the system works normally. Any suggestions? I have used both type of congif, simple or detailed but both didn't work.

**Comment by bugsounet** [comment]
Hi,
Can you enable debug mode in AMk2 and in A2D ?
Restart you mirror with npm start (if you use pm2 auto script, don't forget to stop it)
and give me frond end last log when freeze please ?

**Comment by kondef** [comment]
You mean to run npm start with "dev" and send you the log?

**Comment by bugsounet** [comment]
Mean set `debug: true` in AMk2 config and `debug: true` in A2D config
and restart with npm start in terminal (see my lasted post)

thanks for you help

**Comment by kondef** [comment]
@bugsounet  i am sorry for the late reply. So i switched the debug mode to true on both and i restarted. Where can i see the log in order to send it to you?

**Comment by bugsounet** [comment]
Of course

**Comment by kondef** [comment]
> Of course

No, what i ask is where can i find the log in raspberry to send it to you. Where is it saved?

**Comment by renzo79** [comment]
Hello,
 
I had the same problem and I could fix this by deactivating the Module "MMM-NEWPIR". After that the 2Display function works perfect.
You have to switch to the new PIR-Addon wich is now integrated in the new MK2-Version.

**Comment by bugsounet** [comment]
A2D v1.2.0 is now released, please retry with it.
attention: 
  * A2D need AMk2 v3.2.0 to work
  * A2D configuration file is diferent read [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki)
  * it prefered to retry with fresh sources and fresh sample config file
