### ISSUE TITLE
Display not turning off if ecoMode=false (screen module)

### ISSUE THREAD

**Issue by lxne** [bugsounet/MMM-Assistant2Display#70]
set ecoMode: false is just countdown, without turn off display.

_Originally posted by @JSLEE0413 in https://github.com/bugsounet/MMM-Assistant2Display/issues/13#issuecomment-612436628_

Hi, I do have this issue on my rpi 3b+.
Display is only turning off if ecoMode is true.
With the settings below countdown counts to 0 but screen does not turn off.
If something moves countdown starts anew.

Do I misunderstand ecoMode?

Installed everything form scratch without errors.
_Hardware: rpi 3b+, ReSpeaker 2-mic hat, Grove Gesture Sensor, Grove PIR Motion Sensor
System: Buster, MagicMirror 2.11.0, MMM-GoogleAssistant & MMM-Assistant2Display_

Settings for screen module:
 ```
                               screen: {
                                        useScreen: true,
                                        delay: 1 * 60 * 1000,
                                        turnOffDisplay: true,
                                        ecoMode: false,
                                        displayCounter: true,
                                        text: "Auto Turn Off Screen:",
                                        displayBar: true,
                                        displayStyle: "Text",
                                        detectorSleeping: true,
                                        governorSleeping: false,
                                        rpi4: false
                                },
```

**Comment by lxne** [comment]
Hi, I do have this issue on my rip 3b+.
Display is only turning off if ecoMode is true.
With the settings below countdown counts to 0 but screen does not turn off.
If something moves countdown starts anew.

Do I misunderstand ecoMode?

Installed everything form scratch without errors.
Hardware: rpi 3b+, ReSpeaker 2-mic hat, Grove Gesture Sensor, Grove PIR Motion Sensor
System: Buster, MagicMirror 2.11.0, MMM-GoogleAssistant & MMM-Assistant2Display

screen: settings
 ```
                               screen: {
                                        useScreen: true,
                                        delay: 1 * 60 * 1000,
                                        turnOffDisplay: true,
                                        ecoMode: false,
                                        displayCounter: true,
                                        text: "Auto Turn Off Screen:",
                                        displayBar: true,
                                        displayStyle: "Text",
                                        detectorSleeping: true,
                                        governorSleeping: false,
                                        rpi4: false
                                },
```

**Comment by bugsounet** [comment]
ok, i will try

**Comment by bugsounet** [comment]
humm, confirmed.
I will debug it

**Comment by bugsounet** [comment]
@lxne : i have fixed the npm screen library
can you update A2D and retry ?

`npm run update` inside A2D directory

[npm screen library is now v1.0.2](https://github.com/bugsounet/screen)

**Comment by lxne** [comment]
@bugsounet : Updated, tested, working.

Thank you!
