### ISSUE TITLE
My YouTube video quality isn't great

### ISSUE THREAD

**Issue by OhAye** [bugsounet/MMM-Assistant2Display#72]
Hi,

When I get a YouTube video to run, the quality isn't that great. Is there a way to make the video quality better?

Thanks

**Comment by bugsounet** [comment]
hi, there is no setting for this.
it depends :
 * Internet Quality link
 * Memory Free / CPU Free
 * OpenGL Actived or not

-> YouTube API autoselect quality

**Comment by OhAye** [comment]
Thanks for replying!

My Internet quality is fine (I've got fibre and i'm right next to my router)
Memory and CPU look to be fine as well (New Raspberry Pi 4)
I'm not sure about this step, how do I check?

**Comment by majik655** [comment]
> I'm not sure about this step, how do I check?

In terminal type   sudo raspi-config
go to advanced options
go to OPEN GL 
choose FULL KMS  driver ...

dont know if you have to reboot for it to work (I dont think you do).

**Comment by lxne** [comment]
> choose FULL KMS driver

Full kms is not available on pi4.
Default is fake kms (fkms).
You can double-check it in your config.txt.
A reboot is needed for changes to take effect.

**Comment by OhAye** [comment]
So I would select fake kms?

**Comment by lxne** [comment]
> So I would select fake kms?

Yes, but it is probably already selected.

With mesa tools you can check if direct rendering is active.
Installing mesa tools: `sudo apt-get install mesa-utils`
Check if direct rendering is active: `glxinfo  | grep rendering`

**Comment by bugsounet** [comment]
We think that your main issue is now solved. reopen this issue if needed
