### ISSUE TITLE
Spotify issue

### ISSUE THREAD

**Issue by Mo7aaa** [bugsounet/MMM-Assistant2Display#73]
after typing `npm run spotify`
output:
npm ERR! missing script: spotify
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-03T18_15_55_673Z-debug.log

**Comment by bugsounet** [comment]
It's a `!!! DEV !!!` (for my beta tester users) and it's not yet released
it's writing and explain on wiki spotify page.

**Comment by bugsounet** [comment]
Hi,
A2D with spotify support is now released (v2.1.0)
use `npm run update` before trying to configure it ;)

**Comment by Mo7aaa** [comment]
thank you @bugsounet
