### ISSUE TITLE
How to open a video on youtube with A2D

### ISSUE THREAD

**Issue by phihaidev** [bugsounet/MMM-Assistant2Display#78]
I have installed 2 modules, MMM-GoogleAssistant and MMM-Assistant2Displayant, but I cannot open a video on youtube with google assistant, here is my config of 2 modules
{
  			module: "MMM-GoogleAssistant",
  			position: "fullscreen_above",
  			config: {
    				debug: false,
    				assistantConfig: {
      					lang: "en-US",
      					projectId: "", // Required to use gaction.
      					modelId: "", // (OPTIONAL for gaction)
      					instanceId: "", // (OPTIONAL for gaction)
      					latitude: 10.733867,
      					longitude: 107.184015,
    					},
    				responseConfig: {
      					useScreenOutput: true,
      					screenOutputCSS: "screen_output.css",
      					screenOutputTimer: 5000,
      					activateDelay: 250,
      					useAudioOutput: true,
      					useChime: true,
      					newChime: false,
      					useNative: true,
      					playProgram: "mpg321"
    					},
    				micConfig: { // put there configuration generated by auto-installer
      					recorder: "arecord",
      					device: "plughw:2",
    					},
    				customActionConfig: {
      					autoMakeAction: false,
      					autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      					actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    					},
    				snowboy: {
      					audioGain: 2.0,
      					Frontend: true,
      					Model: "jarvis",
      					Sensitivity: 1.0
    					},
    				A2DServer: {
      					useA2D: true,
      					stopCommand: "stop"
    					},
    				recipes: [ "with-MMM-TelegramBot.js" ]
  				},
		},
		{
  			module: "MMM-Assistant2Display",
  			position: "top_left",
  			config: {
    				debug:false,
    				useYoutube: true,
    				links: {
      					useLinks: true,
      					displayDelay: 60 * 1000,
      					scrollStep: 25,
      					scrollInterval: 1000,
      					scrollStart: 5000,
      					scrollActivate: false,
      					verbose: false
    					},
    				photos: {
      					usePhotos: false,
      					displayDelay: 10 * 1000
    					},
    				volume: {
      					useVolume: true,
      					volumePreset: "ALSA",
      					myScript: null
    					},
    				briefToday: {
      					useBriefToday: false,
      					welcome: "brief Today"
    					},
    				screen: {
      					useScreen: false,
      					delay: 5 * 60 * 1000,
      					turnOffDisplay: true,
      					ecoMode: true,
      					displayCounter: true,
      					displayBar: false,
      					displayStyle: "Text",
      					text: "Auto Turn Off Screen:",
      					detectorSleeping: false,
      					governorSleeping: false,
      					rpi4: false
    					},
    				pir: {
      					usePir: false,
      					gpio: 21,
      					reverseValue: false
    					},
    				governor: {
      					useGovernor: false,
      					sleeping: "powersave",
      					working: "ondemand"
    					},
    				internet: {
      					useInternet: false,
      					displayPing: false,
      					delay: 2* 60 * 1000,
      					scan: "google.com.vn",
      					command: "pm2 restart 0",
      					showAlert: true
    					},
    				TelegramBot: {
      					useTelecastSound: false,
      					TelecastSound: "TelegramBot.ogg"
    					},
    				cast: {
      					useCast: false,
      					castName: "MagicMirror_A2D",
      					port: 8569
    					},
    				spotify: {
      					useSpotify: false,
      					useIntegred: false,
      					useLibrespot: false,
      					connectTo: null,
      					playDelay: 3000,
      					minVolume: 10,
      					maxVolume: 100,
      					updateInterval: 1000,
      					idleInterval: 10000,
      					username: "",
      					password: "",
      					CLIENT_ID: "",
      					CLIENT_SECRET: "",
      					deviceDisplay: "Listening on",
      					usePause: true
    					}
  				},
		},

**Comment by lxne** [comment]
@phihaidev, you might encounter the same issue as I am.

Is your query something like "Play a video ..."?
How is your GA reacting to the query?

**Comment by bugsounet** [comment]
@phihaidev : what do you say for 'open a video on youtube' ?

**Comment by phihaidev** [comment]
@bugsounet I said "jarvis, open the attention song on youtube", but it didn't open, when I searched for information on wikipedia it only displayed a small frame, not a large frame like your screenshot

**Comment by phihaidev** [comment]
@bugsounet Yes, I said I opened the sugar song on YouTube, but it didn't show any results

**Comment by lxne** [comment]
> @bugsounet Yes, I said I opened the sugar song on YouTube, but it didn't show any results

I had the same issue.
After a lot of testing I figured it has something to do with my Google Account I used to authenticate with.
After I tried another Google Account for the authentication process youtube videos are working fine.

```
cd ~/MagicMirror/modules/MMM-GoogleAssistant
mv token.json token.json.old
node auth_and_test.js
```
And try to use another Google Account for authentication.

**Comment by lxne** [comment]
@phihaidev Did you try it and did it work?

**Comment by phihaidev** [comment]
@lxne I don't use youtube anymore because I think it doesn't matter
