### ISSUE TITLE
Close or hide spotify after playing?

### ISSUE THREAD

**Issue by majik655** [bugsounet/MMM-Assistant2Display#79]
Is there a way to have spotify close or hide once I tell GA to "stop" or "thank you"?
Currently I am using spotify module (MMM-Spotify) which does open and plays music but when I tell GA "Thank you" it basically only pauses the spotify module that shows up when playing music.
Because it is paused I am thinking that is why the module will not go away?  Or am I doing something wrong?
(I originally tried to not install spotify module and just use useinegrated but it kept telling me the browser could not use web player and to switch browsers (which I could not figure out)) ...in any case I seem to only get it to play music if I install the spotify module and use the below config.))

**Assistant2display**
```
		{
  			module: "MMM-Assistant2Display",
  			position: "bottom_bar",
  			config: {
    				debug:false,
				useYoutube: true,
    				links: {
      					useLinks: true,
      					displayDelay: 60 * 1000,
      					scrollStep: 25,
      					scrollInterval: 1000,
      					scrollStart: 5000,
      					scrollActivate: false,
      					verbose: false
  					},
				spotify: {
      					useSpotify: true,
      					useIntegred: false,
      					useLibrespot: true,
      					connectTo: "librespot",
      					playDelay: 3000,
      					minVolume: 10,
      					maxVolume: 100,
      					updateInterval: 1000,
      					idleInterval: 10000,
      					username: "MYUSERNAME-WORKING",
      					password: "MYPASSWORD-WORKING",
      					CLIENT_ID: "MYIDISHEREAND-WORKING",
      					CLIENT_SECRET: "MYKEYISHEREAND-WORKING",
      					deviceDisplay: "Listening on",
					usePause: true
    					},
				cast: {
    					useCast: true,
    					castName: "MagicMirror_A2D",
    					port: 8569
  				},

			}
		},
```

**Spotify Module** 

```
		{
  			module: "MMM-Spotify",
  			position: "top_right", // "bottom_bar" or "top_bar" for miniBar
  			config: {
    				debug: false, // debug mode
    				style: "default", // "default" or "mini" available (inactive for miniBar)
    				control: "default",
    				accountDefault: 0, // default account number, attention : 0 is the first account
    				updateInterval: 1000, // update interval when playing
    				idleInterval: 30000, // update interval on idle
    				onStart: null, // disable onStart feature with `null`
    				deviceDisplay: "Listening on", // text to display in the device block (default style only)
    				allowDevices: [], //If you want to limit devices to display info, use this.
    			// allowDevices: ["RASPOTIFY", "My iPhoneX", "My Home speaker"],
    				//miniBarConfig: {
      				//album: true, // display Album name in miniBar style
      				//scroll: true, // scroll title / artist / album in miniBar style
      				//logo: true, // display Spotify logo in miniBar style
    				//	}
  				}
		 },
```

**Comment by bugsounet** [comment]
hi, this feature is reserved with spotify Integred visual of A2D and `usePause: false` feature
in all case, librespot turn off after 10 min and it will be module will be hidden (forced disconnected by librespot)

**Comment by majik655** [comment]
> 
> 
> hi, this feature is reserved with spotify Integred visual of A2D and `usePause: false` feature
> in all case, librespot turn off after 10 min and it will be hidden (forced disconnected by librespot)
> 
> Note: I don't really test the link with A2D with spotify support and MMM-Spotify ... so, it can have some bug
> I will try in a few days

Thank you for your reply...
So if I understand you right using spotify module and my current config the module will timeout after 10minutes (which it did sorry I did not wait long enough to figure that out during my testing lol)..

I keep reading or trying to understand the "integrated" part of assistant2display...
Does it make sense that if I try to use useinegrated that it brings up a browser but can't play it because the browser says web player not supported?  Is that the part you are refering to when you are saying you will "test the link with A2D "?

**Comment by bugsounet** [comment]
hi, I have updated MMM-Spotify with my lastest library. the problem sould be done now (v1.5.0+)

Reopen Issue if needed
