### ISSUE TITLE
not displaying link 

### ISSUE THREAD

**Issue by ahmadmutzakhisyah** [bugsounet/MMM-Assistant2Display#80]
hi I have a problem with MMM-Assistant2Display which is not displaying a link when receiving the command only displays a black screen, please help me, thank you for your attention

**Comment by bugsounet** [comment]
Hi,
Maybe [this part](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration#magicmirror-configuration) is forget ?

**Comment by ahmadmutzakhisyah** [comment]
okay this has worked for me, sorry if it bothered you
