### ISSUE TITLE
MMM assistant2display help install

### ISSUE THREAD

**Issue by brusslesprouts** [bugsounet/MMM-Assistant2Display#82]
So i got MMM-GoogleAssistant working and now trying to get assistant2display working. I copied the simple configuration to my config.js and it boots up fine and jarvis works almost half the time but works.  My question is on the bottom of the instructions it says to add this to my main config file. When i do i get a error when booting my MM says i need a config file any idea?

{
  module: "MMM-GoogleAssistant",
  position: "fullscreen_above",
  config: {
    debug: false,
    ...
    A2DServer: {
      useA2D: true,
    }
  }
},

**Comment by brusslesprouts** [comment]
its also showing in my npm start script that assistant2display is disabled

[2020-07-08 18:52:57.538] [LOG]    [ASSISTANT] Google Assistant is initialized.
[2020-07-08 18:52:57.565] [LOG]    [A2D] MMM-Assistant2Display Version: 2.1.1
[2020-07-08 18:52:57.567] [LOG]    [A2D] Assistant2Display is disabled.

**Comment by lxne** [comment]
You probably have a syntax error in your config.js.
Can you paste the whole content here?

**Comment by bugsounet** [comment]
I think that you put directly the posted config ... and it's really wrong...
please [Read](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration-Sample#for-mmm-googleassistant) this part

**Comment by brusslesprouts** [comment]
here is part of my config 

		},
		{
  module: "MMM-GoogleAssistant",
  position: "fullscreen_above",
  config: {
    assistantConfig: {
      latitude: 37.440319,
      longitude: -121.912231,
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:2",
    },
    {
  module: "MMM-Assistant2Display",
  position: "top_left",
  config: {
    debug:false,
  }
},
  }
},

	]
};

**Comment by brusslesprouts** [comment]
> I think that you put directly the posted config ... and it's really wrong...
> please [Read](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration-Sample#for-mmm-googleassistant) this part
> It's not a sample config but a configuration piece.
> I correct the wiki part for this

update: so i deleted whats above and added 
A2DServer: {
  useA2D: true,
} 
to the assistant part of the config.js as shown below and it boots up but am not able to test it right now.

  module: "MMM-GoogleAssistant",
  position: "fullscreen_above",
  config: {
    assistantConfig: {
      latitude: 37.440319,
      longitude: -121.912231,
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:2",
      A2DServer: {
  useA2D: true,
}
    },
  }
},

**Comment by bugsounet** [comment]
and now, why do you put A2DServer part in your micConfig part ?

**Comment by brusslesprouts** [comment]
to send info to assitant2display?

**Comment by bugsounet** [comment]
sure ... but don't put it in micConfig part :)
like that:
```js
config: {
  assistantConfig: {
  ...
  },
  micConfig: {
  ...
  },
  A2DServer: {
  ...
  }
}
```

**Comment by brusslesprouts** [comment]
Cool will try when i get home thank you.

**Comment by brusslesprouts** [comment]
so i got it working it starts up ill say jarvis show me a youtube video of queen and it just shows me information about queen the band

**Comment by lxne** [comment]
@brusslesprouts 
Is the A2D configuration in your config.js?

```
{
  module: "MMM-Assistant2Display",
  position: "top_left",
  config: {
    debug:false,
  }
},
```

**Comment by brusslesprouts** [comment]
> @brusslesprouts
> Is the A2D configuration in your config.js?
> 
> ```
> {
>   module: "MMM-Assistant2Display",
>   position: "top_left",
>   config: {
>     debug:false,
>   }
> },
> ```

ughh user error... thanks lol got it working youtube videos play now but very choppy

**Comment by nguyenanhminh97** [comment]
I had a similar problem, GA gave me a youtube link without opening the video
Here is the config section

> 

> 

> 

> {

> 			  module: "MMM-GoogleAssistant",
> 			  position: "fullscreen_above",
> 			  config: {
> 			    assistantConfig: {
> 			      latitude: 10.82302,//51.508530,
> 			      longitude: 106.62965,//-0.076132,
> 			    },
> 			    A2DServer: {
> 			      useA2D: true,
> 			      stopCommand: "stop"
> 			    },
> 			    snowboy: {
> 			      audioGain: 2.0,
> 			      Frontend: true,
> 			      Model: "jarvis",
> 			      Sensitivity: null
> 			    },
> 			  }
> 		},
> 		{
> 		  module: "MMM-Assistant2Display",
> 		  position: "top_left",
> 		  config: {
> 		    debug:false,
> 		  }
> 		},

>

**Comment by nguyenanhminh97** [comment]
I fixed it with useYouTube: true
Thanks!

**Comment by bugsounet** [comment]
euh, `useYouTube: true` is not a feature
it's `useYoutube: true` but it's enable by default

**Comment by nguyenanhminh97** [comment]
> euh, `useYouTube: true`không phải là một tính năng
> , `useYoutube: true`nhưng nó được bật theo mặc định

I don't know but when it comes to config.js it works
By the way, I can't turn off the video playing with "stop", am I missing any steps?

**Comment by nguyenanhminh97** [comment]
> euh, `useYouTube: true`không phải là một tính năng
> , `useYoutube: true`nhưng nó được bật theo mặc định

I don't know but when it comes to config.js it works
By the way, I can't turn off the video playing with "stop", am I missing any steps?

**Comment by bugsounet** [comment]
Just change `stopCommand` value into your language in GA configuration
see [There](https://github.com/bugsounet/MMM-GoogleAssistant/wiki/Configuration-Structure#field-a2dserver)

**Comment by bugsounet** [comment]
@brusslesprouts : 
> ughh user error... thanks lol got it working youtube videos play now but very choppy

Do you turn on Video Accelerator on raspi-config (OpenGL)?

**Comment by brusslesprouts** [comment]
> @brusslesprouts :
> 
> > ughh user error... thanks lol got it working youtube videos play now but very choppy
> 
> Do you turn on Video Accelerator on raspi-config (OpenGL)?

I did not I will look into it when I get home thanks for the tip.

**Comment by brusslesprouts** [comment]
> @brusslesprouts :
> 
> > ughh user error... thanks lol got it working youtube videos play now but very choppy
> 
> Do you turn on Video Accelerator on raspi-config (OpenGL)?

**Comment by brusslesprouts** [comment]
what is the voice command to end a youtube video?

**Comment by bugsounet** [comment]
hi, it's write on the [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki#notes)
