### ISSUE TITLE
Displaying YouTube

### ISSUE THREAD

**Issue by mattx38** [bugsounet/MMM-Assistant2Display#9]
Hello, 
Great module for displaying images, but I cannot make YouTube playing videos.
When I ask Jarvis to show me a specific video on YouTube, I can see YouTube just for half a second, then AMk2 take the hand again ans tell me there are results on YouTube, then close.

What could be the solution ?

**Comment by bugsounet** [comment]
hi, can i have a maximum information ?
like : ui used, addons (if used)
modules used ?

and give me front end log please

**Comment by mattx38** [comment]
Hello,
The UI is AssistantMk2 and the only addon is MMM-Assistant2Display.
Modules I use on my MMM : 
-MMM-Remote-Control
-MMM-PIR-Sensor
-MMM-Hotword
-MMM-AssistantMk2
-MMM-Assistant2Display
-calendar
-MMM-CountEvents
-currentweather
-weatherforecast
-MMM-VigilanceMeteoFrance
-MMM-Domoticz
-MMM-Strava
-newsfeed

How can I give you th "front end log" ?
I'm a beginner...

**Comment by bugsounet** [comment]
Je pense savoir d'ou viens le problème, je suis en train de coder justement la partie de gestion de l'ecran.

(je parle dans notre langue natale car je vois que vous êtes Français !)

Merci d'attendre la prochaine version, il y aura beaucoup de changement.

Pour le bug, pour le moment, il manque un composant que j'ai pas pensé lors de la programmation.
La prochaine version devrait sortir ce weekend, je pense.

Je reviens vers vous dès qu'elle est mise en ligne.

Cédric

**Comment by mattx38** [comment]
Super ! 
Merci.

Bravo pour tous ces développements. Je suis admiratif et heureux de pouvoir en profiter.
Merci encore

**Comment by bugsounet** [comment]
A2D v1.2 est maintenant en ligne !
n'oubliez pas de mettre a jour AssistantMk2 a jour (v3.2.0)

Comme je disais, la configuration est totalement différente,
Lisez le [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki)
Il est preférable de redémarrer la configuration avec une nouvelle installation
```sh
cd ~/MagicMirror/modules
rm -rf MMM-Assistant2Display
```
et également supprimer l'ancien champ de configuration de votre `config.js`
et reprendre l'une installation normale depuis le [wiki](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Installation#installation-v120)

En cas de souci, n'hésitez pas à revenir vers moi

**Comment by mattx38** [comment]
Bonjour,
 
J'ai suivi les différents wiki pour mettre à jour/réinstaller les modules A2D, AMk2 et Hotword. Tout s'est très bien déroulé et surtout, ça fonctionne à merveille.
Je peux demander à ce gentil Jarvis d'afficher des images et de jouer des vidéos.

Je suis impressionné par la qualité de ces modules. Bravo pour ces développements !
Merci beaucoup.

Je sens que Jarvis va avoir du boulot avec mes enfants avec ce confinement ;-)
