### ISSUE TITLE
No sound when playing Youtube

### ISSUE THREAD

**Issue by artomka** [bugsounet/MMM-Assistant2Display#93]
Hi, I cannot hear an audio during playing the YouTube videos. Any suggestions how I can solve it, please? :)

**Comment by TheLaurenBarger** [comment]
Hello, 

I'm experiencing the same issue. Thank you @artomka for opening the thread here, and apologies for originally posting the issue in the wrong place :)

**Comment by lxne** [comment]
What does your GA and A2D config look like and what is your output device?

**Comment by artomka** [comment]
I use HiFiBerry DAC+ audio output and this is my config:

            ```
  {
		  module: "MMM-GoogleAssistant",
		  position: "fullscreen_above",
		  config: {
			assistantConfig: {
			  latitude: ...,
			  longitude: ...,
			  projectId: "...",
			  modelId: "...",
			  instanceId: "...",
			},
			responseConfig: {
			  screenOutputTimer: 2000,
			  activateDelay: 250,
			  useChime: false,
			},
			micConfig: {
			  recorder: "arecord",
			  device: "plughw:1",
			},
			snowboy: {
			  audioGain: 1.0,
			  Frontend: false,
			  Model: "smart_mirror",
			  Sensitivity: 0.3
			},
			A2DServer: {
			  useA2D: true,
			  stopCommand: "stop"
			},
			recipes: [
				"with-MMM-TelegramBot.js", "with-MMM-Spotify"
			],
		  }
		},
                {
		  module: "MMM-Assistant2Display",
		  position: "top_left",
		  config: {
			debug:false,
			volume: {
			  useVolume: true,
			  volumePreset: "HIFIBERRY-DAC", (I have tried ALSA as well.)
			},
			cast: {
			  useCast: true,
			  castName: "...",
			  port: 8569
			},
			spotify: {
			  useSpotify: true,
			  useIntegred: true,
			  username: "...",
			  password: "...",
			  CLIENT_ID: "....",
			  CLIENT_SECRET: "...",
			  deviceDisplay: "Listening on",
			  usePause: true,
			}
		  }
		},
```

**Comment by bugsounet** [comment]
Hi, have you set your output device in your RPI desktop ?
volume icon> output device > select your device
in the same same select mixer to volume control

**Comment by lxne** [comment]
You could try `useNative: true` in the GA config.
It might help. Check the GA wiki.

**Comment by bugsounet** [comment]
It's for GA audio response not for A2D sound output ;)
so not in this case ;)

**Comment by lxne** [comment]
> It's for GA audio response not for A2D sound output ;)

Goog to know!

**Comment by bugsounet** [comment]
I can't do that, because YT API use HTML5 (google want this)

**Comment by artomka** [comment]
> Hi, have you set your output device in your RPI desktop ?
> volume icon> output device > select your device
> in the same scheme select mixer to volume control
> 
> I think it should playing in the wrong output

Yes, look :)

![F48EA648-5530-406F-8281-F0C9543DF24D](https://user-images.githubusercontent.com/41210608/88265651-2e47ad00-ccce-11ea-8aaa-0a6e6930590b.jpeg)

**Comment by artomka** [comment]
BTW: If you have some free time, you can check my waterproof MagicMirror project on YouTube: https://youtu.be/MtECTogXJsw

**Comment by lxne** [comment]
@artomka Did you resolve the issue?
Is the assistant audio response working?
Do you get audio in your browser (e.g. youtube)?
