### ISSUE TITLE
Module Spotify Probléme

### ISSUE THREAD

**Issue by Symbiotes1** [bugsounet/MMM-Assistant2Display#97]
Bonjour,
J'ai une erreur quand je veux ajouter le module spotify ? Auriez-vous une idée ? 
![Capture](https://user-images.githubusercontent.com/51495509/88487083-7a227c80-cf82-11ea-89bc-d1de5c071753.JPG)

Je pense que j'ai du mal faire un truc.

Merci.

**Comment by bugsounet** [comment]
bonsoir,

oui effectivement, vous avez placer la configuration du sous-module Spotify en dehors de la configuration générale de Assistant2Display
il faut donc mettre votre configuration de spotify a l'intérieur de `config {}` 
L'exemple de configuration [complete](https://github.com/bugsounet/MMM-Assistant2Display/wiki/Configuration-Sample#full--detailed-see-the-configuration-structure) pourra vous aider

**Comment by Symbiotes1** [comment]
Rebonsoir, 
Se fichier "Config" il doit se trouver dans Assitant2Display ? 
![Capture](https://user-images.githubusercontent.com/51495509/88487827-d8eaf480-cf88-11ea-83c3-b0347247367f.JPG)

**Comment by bugsounet** [comment]
dans `~/MagicMirror/config/config.js`

**Comment by Symbiotes1** [comment]
Rebonsoir,

J'ai essayer de m'inspirer de la configuration complete, mais je n'y suis toujours pas..
![Capture](https://user-images.githubusercontent.com/51495509/88487977-55320780-cf8a-11ea-93cf-c4d1791940ff.JPG)

**Comment by bugsounet** [comment]
Quel est le problème ?

**Comment by Symbiotes1** [comment]
J'ai toujours se message d'erreur..
![Capture](https://user-images.githubusercontent.com/51495509/88488210-038a7c80-cf8c-11ea-8917-7b0cec8cd582.JPG)

**Comment by bugsounet** [comment]
Je ne vois pas de problème particulier.... Mise à part que vous avez mis un $ de trop quand vous avez lancer l installation 
Par contre, vous n avez pas renseigné les champs CLIENT dans votre config
Sûrement un oubli ;)

**Comment by Symbiotes1** [comment]
Oui effectivement oublie de ma part, et de plus le dollar... quel heure..
Cela à fonctionner, merci de votre assistance et de votre temps.

Merci,

**Comment by bugsounet** [comment]
pas de souci, bonne utilisation a vous !
