### ISSUE TITLE
Spotify ne s'ouvre pas

### ISSUE THREAD

**Issue by Symbiotes1** [bugsounet/MMM-Assistant2Display#98]
Bonsoir, 
J'ai installer le module hier et tout fonctionne pas de soucis l'a dessus. 
Mais je demande à l'assistant de mettre une musique il me mais juste une recherche et ne la lance pas : 
![Capture](https://user-images.githubusercontent.com/51495509/88589374-52eaae80-d059-11ea-8680-0c0f0fad53c2.JPG)

**Comment by bugsounet** [comment]
Bonsoir,

d’après votre dernière configuration
      `useSpotify` , `useIntegred`, `useLibrespot` étaient sur `false`

Si vous ne n'avez rien changé cela peut être la source du souci

Pour rappel : `false` -> désactivé , `true`-> activé
rapportez vous sur [wiki du sous-module spotify](https://github.com/bugsounet/MMM-Assistant2Display/wiki/spotify#configuration-of-the-module) pour plus d'aide

**Comment by Symbiotes1** [comment]
Effectivement, mais toujours le même soucis pareille pour la radio, j'ai repris un screen de la config actuelle. 
![2](https://user-images.githubusercontent.com/51495509/88592946-17eb7980-d05f-11ea-8b9b-71e3ef1ce99b.JPG)
![Capture](https://user-images.githubusercontent.com/51495509/88592950-191ca680-d05f-11ea-9b18-3d4fe5f9c33e.JPG)

**Comment by Symbiotes1** [comment]
Je vient aux nouvelles, une idée du problème ?

**Comment by bugsounet** [comment]
Oui car vous ne voulez pas tout simplement lire le wiki

1) `connectTo: default device for playing audio (if not connected). example "Librespot". (premium member only)`
si il est sur `null`, cela veux dire aucun lecteur ...
2) vous utilisez:
  *  le recipe de MMM-Spotify
  * celui d'A2D -> `useIntegred: activate visual of the current playback`
il va faloir faire un choix, soit celui d'A2D soit celui de spotify
car dans votre config, vous utilisez les 2.

Malheureusement, si vous ne faites pas d'effort, je ne pourrais faire plus ...
Le programme est télécharger plus de 500 fois par semaine! 
Si il y aurait un souci réél, il serai deja remonté depuis longtemps
Sachez qu'un souci de configuration n'est pas une issue pour moi
Je traite en priorité les issues réels (probleme lié au code maitre)
Hors la non lecture du wiki n'est pas une issue
désolé de vous faire réagir
