### ISSUE TITLE
youtube not responding

### ISSUE THREAD

**Issue by lazyscorpion** [bugsounet/MMM-Assistant2Display#99]
![Untitled](https://user-images.githubusercontent.com/41412558/88823696-ffa46780-d1e2-11ea-8726-ae8f31c6b184.png)
hi... been trying to open youtube videos through voice command but the screen is getting kind of stuck... 
getting this error.. youtube cast is working.. 

[2020-07-29 21:00:16.435] [LOG]    [CAST] PONG YouTube {
  name: 'YouTube',
  state: 'stopped',
  allowStop: true,
  pid: null,
  launch: [Function: launch]
}

**Comment by bugsounet** [comment]
Hi, it's an error
It just says Cast module receive some data
just because youtube app will scan all device who can be casted

It's not depend of YouTube module

**Comment by lazyscorpion** [comment]
been trying to play a video from youtube through voice command.. when i tried to give a command the GA keeps showing the loading screen.. no other response till i restart the magicmirror.. if given a command anything related to a video the screen juss keeps loading and nothing else.. am stuck at the loading screen as shown below


![Untitled](https://user-images.githubusercontent.com/41412558/88879796-ca326500-d248-11ea-8599-1a41c5a6df50.png)

**Comment by bugsounet** [comment]
What's RPI device do you use ? (needed RPI 3B+ and more)
You are running MagicMirror in low resolution and needed mini 720p for GA/A2D
and it's a problem for it

**Comment by lazyscorpion** [comment]
Hi.. Am running RPI 4B 4GB ram
My resolution is 1680x1050
Am still having the same problem... 
Getting stuck when asked for a video or any related query... 

![IMG_20200805_141940_247.jpg](https://user-images.githubusercontent.com/41412558/89392556-5223dd80-d727-11ea-9840-3b2a93dca5b2.jpg)

**Comment by bugsounet** [comment]
try to updating GA/A2D.

don't forget to set `screenRotate: true,` in the GA responseConfig field config
It will correct your weird screen displaying :)

**Comment by tdungsi1** [comment]
Hello, 
When I play something on youtube, a new page appeared and disappeared immediately. Is there a way to fix this problem? 
Thank you

![image](https://user-images.githubusercontent.com/26120816/92465764-3e253d00-f1f9-11ea-91d1-0084cd0fcad3.png)

**Comment by bugsounet** [comment]
Hi, Wiki configuration part is ok ?

what's the `address` field ?
what's the `electronOptions` ?
to do try to turn on `OPENGL` ?

**Comment by sansamy** [comment]
salut j ai 1 pi3b et youtube tourne assez lentement, le pi 4 de 4 gigas ferait l affaire ? Je voulais prendre le  gigas mais je crois que chromium va pas dessus si j ai bien compris et cest en 64 bits je c pas si compatible avec votre module , merci

**Comment by tdungsi1** [comment]
![image](https://user-images.githubusercontent.com/26120816/92713497-3d211680-f385-11ea-8488-6eab8885b954.png)

OPENGL is working.
I did everything. But Youtube still doesn't work. Youtube display the video for 1 second then closed it immediately.
Thanks for helping.

**Comment by bugsounet** [comment]
2 choices:

1) I make a fake module
2) You don't read wiki 

so ?

**Comment by tdungsi1** [comment]
Yes I'm sorry. It's my issue. If you point out which section contains the information, I will stop asking such question. Because I literally can't find the information in wiki.

**Comment by tdungsi1** [comment]
I read everything. :(

**Comment by bugsounet** [comment]
sure ?

i see no background,  when you call assistant ...
I think you use MMM-pages

try with out it and if works let's configure it correctly
